### ISSUE TITLE
Superstruct type error with create react app

### ISSUE THREAD

**Issue by fracek** [0xs34n/starknet.js#131]
I noticed that when using this library with a project created with `create-react-app` users get a `TypeError` generated in `typedData`. This doesn't seems to be related to #37.

I created a repo to reproduce this issue [here](https://github.com/fracek/create-react-app-type-error-starknet).

I attached the log file generated by Chrome.
[localhost-1644609483259.log](https://github.com/0xs34n/starknet.js/files/8051312/localhost-1644609483259.log)

**Comment by 0xs34n** [comment]
We should probably replace `superstruct` package

**Comment by arochedy** [comment]
Same error for me. 

I try to add the confg-overrides.js file and the solution from #37 and I still have the problem :(
