### ISSUE TITLE
Add Utilities for Felt Array Conversion

### ISSUE THREAD

**Issue by rzmahmood** [0xs34n/starknet.js#132]
Hey team,

I was wondering if the following utilities would be a good place for this repo:
```js
/**
 * Converts a string into an array of numerical characters in utf-8 encoding
 * @param {string} str - The string to convert
 * @returns {bigint[]} - The string converted as an array of numerical characters
 */
 export function stringToFeltArray(str: string): bigint[] {
  const strArr = str.split('');
  return strArr.map(char => BigInt(Buffer.from(char)[0].toString(10)));
}

/**
 * Converts an array of utf-8 numerical characters into a readable string
 * @param {bigint[]} felts - The array of numerical characters
 * @returns {string} - The readable string
 */
export function feltArrayToString(felts: bigint[]): string {
  return felts.reduce((memo, felt) => memo + Buffer.from(felt.toString(16), 'hex').toString(), '');
}
```
I found these utilities useful for the scenario:
 to convert a `string -> [felt]` so that it can be passed as an argument to a function with parameters: `arg_len: felt, arg: felt*`:

I can create the PR if that works for everyone!

**Comment by rzmahmood** [comment]
@janek26  No, it's not. It was developed in the library by https://github.com/sekai-studio/starknet-libs/tree/7d2a461c7ea6684499a2df9601c6b3c0efa568f9 but could be consolidated here.

Guthl from Starkware suggested proceeding with this here : https://discord.com/channels/793094838509764618/927918707613786162/945417045330239638

**Comment by janek26** [comment]
not sure if it should live in starknet.js then or if it should just be a tiny independent package?
