### ISSUE TITLE
Run tests on localhost

### ISSUE THREAD

**Issue by delaaxe** [0xs34n/starknet.js#134]
It seems unit tests are running against the `defaultProvider` which is goerli, making the tests really slow.

An example of a localhost test runner can be found here: https://github.com/argentlabs/argent-x/blob/develop/.github/workflows/test.yml#L14

**Comment by dhruvkelawala** [comment]
I think running actual tests before publishing a package is better to run on goerli. If you are looking to contribute or test your own feature/change, you can make changes to `defaultProvider` and set the `baseUrl` to `http:localhost:5000`

**Comment by janek26** [comment]
it would be great to run the test suite against some local network for development. I agree we should still do the full run against Goerli (or both) before merge and in the branches.

**Comment by delaaxe** [comment]
Having to make code changes to change test network isn't great, ideally we'd have a different command in package.json

**Comment by janek26** [comment]
agree, lets change code to consume some ENV var and fallback to current behavior

**Comment by dhruvkelawala** [comment]
> agree, lets change code to consume some ENV var and fallback to current behavior 

Or similar to defaultProvider, let's create a testProvider which uses localhost in baseUrl and must only be used for testing. No code changes will be required. :)

**Comment by delaaxe** [comment]
possible to run PR tests against localhost and run npm publishing tests against goerli?

**Comment by janek26** [comment]
I would probably keep both test runs for PR.
I like the idea of keeping develop and main stable, aka make sure things work before merging.

But it would be very helpful for individual devs to run against local devote before creating a PR.

If local tests proof reliable we can discuss about replacing the full test run for PR's again
