### ISSUE TITLE
Why are we passing ABIs when we are not using it in `signTransaction()`?

### ISSUE THREAD

**Issue by dhruvkelawala** [0xs34n/starknet.js#135]
Maybe let's improve documentation around it?

https://github.com/0xs34n/starknet.js/blob/b130516b790e87357143a4c99cf5534386a14a27/src/signer/default.ts#L26

**Comment by janek26** [comment]
that's done to allow Signers to display additional info on an transaction. 
Imagine ledger/argent x

should be covered in docs @0xs34n
