### ISSUE TITLE
Implement Contract methods TS validation based on ABI 

### ISSUE THREAD

**Issue by janek26** [0xs34n/starknet.js#140]
throw an error in starknet.js if input object has additional keys that cant be used as input arguments
https://github.com/seanjameshan/starknet.js/blob/d9ec6d3ea3cc0dbf3538fb2fe7b5e1d8a8831490/src/contract.ts#L76

As a dev it's annoying if you pass an object which looks right but don't get an error.
example: https://github.com/argentlabs/argent-x/pull/382

maybe somebody can pick tis up faster than I can.

**Comment by tabaktoni** [comment]
Creted new Related Issue https://github.com/0xs34n/starknet.js/issues/514 on how to resolve

**Comment by davelange** [comment]
Have you considered using https://github.com/keep-starknet-strange/abi-wan-kanabi for this feature? I [opened an issue ](https://github.com/keep-starknet-strange/abi-wan-kanabi/issues/10) there regarding creating contract instances with type support for methods based on the ABI. Would that be a solution for this issue?

**Comment by haroune-mohammedi** [comment]
I'll be more than happy to take care of this issue
