### ISSUE TITLE
`semantic-release` should publish pre-release versions from develop

### ISSUE THREAD

**Issue by delaaxe** [0xs34n/starknet.js#142]
https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/release-workflow/pre-releases.md#publishing-pre-releases

**Comment by janek26** [comment]
it does by default, eg https://github.com/0xs34n/starknet.js/releases/tag/v3.4.0 is a pre-release

**Comment by delaaxe** [comment]
i meant that the published version name should be something like `v3.0.0-pre4` or `v3.0.0-alpha4` or something
