### ISSUE TITLE
Issue in Deploying Abstract Account Contract using defaultProvider.deployContract

### ISSUE THREAD

**Issue by legion2002** [0xs34n/starknet.js#153]
I am trying to deploy an abstract account 
I am using the compiled Argent Account directly from the the starknet js github repo - https://github.com/legion2002/starknet.js/blob/develop/__mocks__/ArgentAccount.json

Here is the code I am using - 
```
const privateKey = randomAddress();

        const starkKeyPair = ec.getKeyPair(privateKey);
        const starkKeyPub = ec.getStarkKey(starkKeyPair);
        const readContract = (name: string): CompiledContract =>
              JSON.parse(fs.readFileSync(`./test/mocks/${name}.json`).toString('ascii'));
              
        const compiledArgentAccount = readContract('ArgentAccount');
        console.log(`Compiled Contract is: ${compiledArgentAccount.abi}`);

        const accountResponse = await defaultProvider.deployContract({
            contract: compiledArgentAccount,
            addressSalt: starkKeyPub,
        });


        const contract = new Contract(compiledArgentAccount.abi, accountResponse.address);
        // @ts-ignore
        await contract.initialize(starkKeyPub, "0");
```
But I keep getting this error -
![image](https://user-images.githubusercontent.com/64212892/159895952-4403d01d-7813-4758-ac0b-b502c0b3a5c2.png)
my default provider is not undefined, as I have printed the gateway URL from it successfully
the problem to me seems to be in the compiled Argent Account, as I also get this error in vscode
![image](https://user-images.githubusercontent.com/64212892/159895449-565f1b11-54df-47bc-bcc0-745f96022ea4.png)

This is how I am importing from starknet - 
```
import {CompiledContract} from "starknet/types";
import { Signer, Transaction, Provider, ec, AddTransactionResponse, hash, defaultProvider, Contract, stark, json } from "starknet";
```

I am able to log out the compiledArgentAccount and its abi.
I have tried to do everything exactly the same as account.test.ts on the starknet.js repo, but am unable to deploy the contract.
Any help would be appreciated
thanks

**Comment by MilGard91** [comment]
Hey, since this was resolved in the discord channel and it was a problem with starknet.js version I will close this one.
