### ISSUE TITLE
Get an Account from Wallet

### ISSUE THREAD

**Issue by clacladev** [0xs34n/starknet.js#160]
Hello team.
I have a series of wallets defined in `hardhat.config.ts`. I deployed them manually on the devnet. Now I am writing tests and I would like to obtain an `Account` object, from the `Wallet` object obtained from `const ringoWallet = getWallet('Ringo')`.
Is there a way to do so?

**Comment by MilGard91** [comment]
If you have the keys and a address you can:
`const ringoWallet = new starknet.Account(provider, address, keyPairOrSigner)`
For the provider

```
const provider = new starknet.Provider({
    baseUrl: 'http://localhost:5000',
    feederGatewayUrl: 'feeder_gateway',
    gatewayUrl: 'gateway',
})
```

**Comment by janek26** [comment]
answered :)
