### ISSUE TITLE
Function parameter struct arrays can't be used

### ISSUE THREAD

**Issue by microbecode** [0xs34n/starknet.js#164]
If you are trying to call a function which has an array of structs as input parameter, your call will fail.

This is because the code checks whether the `type` is any of the listed `struct` types. It's not, because the type includes the asterisk symbol `*`. Here's an example from OZ account contract: https://github.com/OpenZeppelin/cairo-contracts/blob/dfafdd2ebd778718cf440555e975f6eace278695/src/openzeppelin/account/Account.cairo#L108

The problematic check is here: https://github.com/0xs34n/starknet.js/blob/f9eeee37a18e454011ac3720bd0f4fdafb470c59/src/contract/default.ts#L277

This is critical because the newest `__execute__`  account contract function can't be called.

**Comment by microbecode** [comment]
I was testing, added also some console.logs to your library.
The struct was registered properly, but `input.type` was `AccountCallArray*` instead of `AccountCallArray`. It was registered as struct `AccountCallArray`, so the line 277 (in my original post) didn't see it as a struct.
I got errors that the argument should be of array type (the `else` "fallback" branch at line 294)

**Comment by microbecode** [comment]
I'm a bit puzzled. Your line 293 has an `else` branch (not an `else if`). After that, on line 316 there is another `else` branch. So the branching goes something like this: `if -> else if -> else -> else if -> else`. That doesn't make any sense.

**Comment by janek26** [comment]
> I'm a bit puzzled. Your line 293 has an `else` branch (not an `else if`). After that, on line 316 there is another `else` branch. So the branching goes something like this: `if -> else if -> else -> else if -> else`. That doesn't make any sense.

this is not possible in JS :) if you look closely you can see it's 2 different if statements where the else applies to

**Comment by microbecode** [comment]
Ah heh yes. Even copypasted the code locally to check I was reading it correctly, but didn't help - I was just reading it incorrectly.

But in any case, as far as I can tell, my original bug is valid.

**Comment by MilGard91** [comment]
@microbecode Can you send me how do you call this method? So I can test it out.

**Comment by microbecode** [comment]
Here's a somewhat cleaned version: https://github.com/eqlabs/starknet-multisig/tree/feature/js_bug
Uses OZ Account.cairo , just changed its import paths.

To test (I've been using venv):
`yarn`
`npm run compile`
`npx hardhat test`

**Comment by MilGard91** [comment]
But you are passing an object when the function expects an array. So you should pass `[callArray]` instead of `callArray`

**Comment by microbecode** [comment]
Thanks, but I've already tried all sorts of variants. Tried now again `[callArray]` - same result: `Error: arg call_array should be an Array`

**Comment by MilGard91** [comment]
Remove the _len properties and it should work.

**Comment by microbecode** [comment]
Looks like I interpret the `default.ts` code wrong and got mixed up with different tooling - one requires one to input the array length manually, while another does it for you.

Thanks a lot for the help, things seem to work fine once I remove then `_len` inputs.
