### ISSUE TITLE
Contract factory deploy arguments

### ISSUE THREAD

**Issue by fracek** [0xs34n/starknet.js#180]
I noticed that `ContractFactory.deploy` expects `RawCallData` as input, any particular reason for that? I believe it would be easier to use if it expected arguments like other call methods (`call`, `invoke`) and converted them to raw call data internally.

**Comment by tabaktoni** [comment]
@ivpavici can we close this one? This is done by Iris and refactored in https://github.com/0xs34n/starknet.js/pull/498
