### ISSUE TITLE
Assertion Error: normalize_address() cannot be used with the current constants

### ISSUE THREAD

**Issue by wantedsystem** [0xs34n/starknet.js#181]
Hello,

I've used the latest version of https://github.com/0xs34n/starknet.js-workshop example in a react web application using starknet.js version 3.10.2, but instead of importing the json files from the file system (I don't have access to the FS), I created a JS module that exports the content of the files as strings and then I parse them as JSON.

I have an error when executing this code (minting tokens to the account address)

<img width="621" alt="Screenshot 2022-04-29 at 14 00 43" src="https://user-images.githubusercontent.com/11537417/165940965-01732bb0-e5ca-4bc5-aa68-8c4c08c683d0.png">

This is the error that i get 

<img width="443" alt="Screenshot 2022-04-29 at 13 31 37" src="https://user-images.githubusercontent.com/11537417/165941017-daeb5fd1-79eb-47ae-982c-83dcdbdf7c1c.png">

<img width="443" alt="Screenshot 2022-04-29 at 13 31 44" src="https://user-images.githubusercontent.com/11537417/165941031-601dfc26-71d6-4a33-ac80-bda302c61049.png">

Do you have any idea how to fix this ?

**Comment by janek26** [comment]
hey, if you import using js, you need to import as txt file, as json's get pased and destroy the bignumbers in the process. After importing as raw text, you can parse them using the json export from the lib

**Comment by zediogoviana** [comment]
I had the same issue, but I was using NextJs. The solution I came up with was to use [API Routes](https://nextjs.org/docs/api-routes/introduction) to make a request to some defined endpoint to read contracts. As this request is handled server-side, you have access to `fs`.

File in `pages/api/contract.ts`
```
import { NextApiRequest, NextApiResponse } from "next";
import nc from "next-connect";
import {json} from "starknet";

const handler = nc<NextApiRequest, NextApiResponse>({
  onError: (err, req, res) => {
    res.status(500).send({ message: "internal server error" });
  },
}).get((_, res) => {
  const fs = require('fs');
  const file = fs.readFileSync("./<pathToContract>/Contract.json");

  res.send({ contract: file.toString("ascii") });
});

export default handler;
```

And then call it like this where we want the correct payload.
```
const resp = await fetch("/api/contract");
const file = json.parse((await resp.json()).contract);  
```

This is different from @wantedsystem 's situation and I'm also not sure if it's the best solution, but just leaving it here, as it might help someone in the future using a similar technology that provides SSR.

**Comment by janek26** [comment]
closed due to inactivity
