### ISSUE TITLE
Perhaps a little silly question: Where can I find ArgentAccount.json?

### ISSUE THREAD

**Issue by KirisakiAria** [0xs34n/starknet.js#194]
![image](https://user-images.githubusercontent.com/20788476/170761491-3ce71074-f0f0-43e2-845f-b3b2787303e8.png)
When I was learning to create accounts with starknetjs, ArgentAccount.json was mentioned here. How can I find that?

**Comment by badurinantun** [comment]
Agent account contract can be found [here](https://github.com/argentlabs/argent-contracts-starknet ).

If you just want to follow along the example you can use the file from the workshop repo: [ArgentAccount.json](https://github.com/0xs34n/starknet.js-workshop/blob/main/ArgentAccount.json).
