### ISSUE TITLE
Incorrect types on `get_transaction` endpoint responses

### ISSUE THREAD

**Issue by Arcticae** [0xs34n/starknet.js#218]
i believe the types in the library are not compliant with the newest API on goerli/mainnet (0.9.0), this one is an example:

In this one there is transaction hash in top level from GetTransactionResponse:
https://github.com/0xs34n/starknet.js/blob/develop/src/types/api.ts#L228

And here it's in the transaction itself:
https://alpha4.starknet.io/feeder_gateway/get_transaction?transactionHash=0x1c104329cc40c94992c816a6c07e8cedd287d5f7c1d901bb7855923e169a00d

**Comment by dhruvkelawala** [comment]
Thanks for reporting this. I will go through all the apis again and fix wherever I find such bugs.

cc: @janek26

**Comment by Arcticae** [comment]
@janek26 @dhruvkelawala 
Hey guys it's still an issue, the responses from the API don't include the hash which is in the transaction object.
https://alpha4.starknet.io/feeder_gateway/get_transaction?transactionHash=0x1c104329cc40c94992c816a6c07e8cedd287d5f7c1d901bb7855923e169a00d

Response:
```
{
   "status":"ACCEPTED_ON_L1",
   "block_hash":"0xadb7f89d94424117eaceca49bae5b1915631d4ae58a6711c69258d89078937",
   "block_number":240519,
   "transaction_index":26,
   "transaction":{
      "contract_address":"0x481eed2e02b1ff19fd32429801f28a59dea630d81189e39c80f2f60139b381a",
      "entry_point_selector":"0x15d40a3d6ca2ac30f4031e42be28da9b056fef9bb7357ac5e85627ee876e5ad",
      "entry_point_type":"EXTERNAL",
      "calldata":[
         "0x1",
         "0x6f2951b163bc1c291dd2d45351070e05ec0b37cb84f3cbd6a2610ae0a202f2",
         "0x362398bec32bc0ebb411203221a35a0301193a96f317ebe5e40be9f60d15320",
         "0x0",
         "0x1",
         "0x1",
         "0xb",
         "0x9"
      ],
      "signature":[
         "0x2ea7f90c685042d2c4b2921f515895e6e352919200ca2621db154aea07d6261",
         "0x534a4c86025416621b726b0efd22b19f87999b8dcecc94cb5b9c66f12ee7445"
      ],
      "transaction_hash":"0x1c104329cc40c94992c816a6c07e8cedd287d5f7c1d901bb7855923e169a00d",
      "max_fee":"0xa38a596a642",
      "type":"INVOKE_FUNCTION"
   }
}
```

**Comment by janek26** [comment]
can you check https://github.com/0xs34n/starknet.js/pull/224 ?
