### ISSUE TITLE
Call Contract - Response parsing on call errors

### ISSUE THREAD

**Issue by Arcticae** [0xs34n/starknet.js#228]
The library tries to parse the response and the code for parsing response throws an error, since response is undefined: 
`Cannot read properties of undefined (reading 'flat')`

This part of code seems to cause the issue:
https://github.com/0xs34n/starknet.js/blob/5374fdf676915d634775c7c072ea923ddaee2817/src/contract/default.ts#L614

**Comment by badurinantun** [comment]
Thanks for opening the issue! What's the thrown error?

**Comment by Arcticae** [comment]
```
TypeError: Cannot read properties of undefined (reading 'flat')
    at Contract.parseResponse (webpack-internal:///./node_modules/starknet/dist/contract/default.js:550:41)
    at eval (webpack-internal:///./node_modules/starknet/dist/contract/default.js:616:59)
    at async eval (webpack-internal:///./node_modules/@starknet-react/core/dist/hooks/call.js:41:20)
```

**Comment by Arcticae** [comment]
https://github.com/0xs34n/starknet.js/pull/232
This one might fix the issue, although it needs to be tested

**Comment by Arcticae** [comment]
@janek26 did this one fix the issue for you? I'm still getting this error after upgrading to newer version with the `GatewayError` introduced

**Comment by Arcticae** [comment]
NVM - i had an older version of package installed :)
