### ISSUE TITLE
When creating an account block in defaultProvider.waitForTransaction 

### ISSUE THREAD

**Issue by Qupday** [0xs34n/starknet.js#241]
const accountResponse = await defaultProvider.deployContract({
        contract: compiledAccount,
        addressSalt: starkKeyPub,
    });
await defaultProvider.waitForTransaction(accountResponse.transaction_hash);

js code block in waitForTransaction function; I query status by hash in "https://alpha4.starknet.io/feeder_gateway/get_transaction_status?transactionHash=hash" first return RECEIVED; and serveral minutes later; It return "{"tx_status": "REJECTED", "tx_failure_reason": {"code": "TRANSACTION_FAILED", "error_message": "Error at pc=0:465:\nAn ASSERT_EQ instruction failed: 10:1 != 10:0."}}"
 What is the problem?

**Comment by badurinantun** [comment]
Can you check the source of your compiled account? Some assert failed in it

**Comment by Qupday** [comment]
Here is my code: Account.json is download from this project in __mocks__/Account.json
const starkKeyPair = ec.genKeyPair();
    const starkKeyPub = ec.getStarkKey(starkKeyPair);

    const compiledAccount = json.parse(
        fs.readFileSync("./Account.json").toString("ascii")
    );

    const accountResponse = await defaultProvider.deployContract({
        contract: compiledAccount,
        addressSalt: starkKeyPub,
    });

    await defaultProvider.waitForTransaction(accountResponse.transaction_hash);

**Comment by Qupday** [comment]
> Can you check the source of your compiled account? Some assert failed in it
Account.json is download from this project in mocks/Account.json..Is it ok?

**Comment by badurinantun** [comment]
Sorry, could not reproduce this issue. Perhaps you can pick a different account artifact, it will be easier to debug when you have a source code
