### ISSUE TITLE
Error Dockerize

### ISSUE THREAD

**Issue by 0xAurelou** [0xs34n/starknet.js#245]
Does some someone tried to dockerize an app using starknet-js ? 
I got this error  
Since I am not used to starknet-js please be nice 
```
#0 6.468 error An unexpected error occurred: "https://registry.yarnpkg.com/get-starknet/-/get-starknet-1.4.2.tgz: getaddrinfo EAI_AGAIN registry.yarnpkg.com".

```

**Comment by badurinantun** [comment]
Did you try to use `npm` instead of `yarn`?

**Comment by janek26** [comment]
closed due to inactivity
