### ISSUE TITLE
Proposal: Add calcChainId() util

### ISSUE THREAD

**Issue by ssteiger** [0xs34n/starknet.js#246]
Proposal:

It would be nice to have a function from which one can fetch/calculate the chain id passing the network identifier as a string.

**example:**

```javascript
import { calcChainId }  from 'starknet'

const l_chainId = calcChainId("SN_LOCALHOST")

const g_chainId = calcChainId("SN_GOERLI")

const m_chainId = calcChainId("SN_MAIN")
```

equivalent python code:
```python
int.from_bytes(b'SN_MAIN', byteorder="big", signed=False) // 23448594291968334
```

* [starknet docs - chain id](https://docs.starknet.io/docs/Blocks/transactions/#chain-id)

**Comment by ssteiger** [comment]
Code

```javascript
import { encodeShortString } from "../utils/shortString";

export const calcChainId = (str: String) => encodeShortString(str);
```

**Comment by badurinantun** [comment]
When would you use this? Chain id can be fetched from the provider, so I'm just wondering what the use case for this is

**Comment by ssteiger** [comment]
In the boilerplate I'm creating there is an array of all starknet networks together with the relevant information that is needed to easily switch between networks. On a switch the js contract objects are updated with the different deployed contracts.
The file looks like this [here](https://github.com/ssteiger/starknet-dapp-boilerplate/blob/main/packages/react-app/src/constants.js).
I'm not entirely sure about this approach yet though.

**Comment by janek26** [comment]
ist this the same as `shortString` which already exists ?

**Comment by ssteiger** [comment]
Yes. Maybe it would be easier though if there was a descriptive function? 
It took me quite some time to find out how to get the chainId.

**Comment by janek26** [comment]
closed as it's part of shortsfring
