### ISSUE TITLE
Cannot invoke contract functions

### ISSUE THREAD

**Issue by Marchand-Nicolas** [0xs34n/starknet.js#250]
Hello, I am new to starknet js.
I'm trying to invoke a function of a contract using this code : 
```js
        const { transaction_hash: transferTxHash } = await account.execute(
            {
                contractAddress: eykarCommunityContract.address,
                entrypoint: "completeQuest",
                calldata: [questId, player],
            },
            undefined,
            { maxFee: "0" }
        );
```
But I get this error: 

```js
TypeError: Cannot read properties of undefined (reading '0')
    at Account.<anonymous> (/home/nicolas/Desktop/Nico/eykar/API/node_modules/starknet/dist/account/default.js:125:92)
```

So I went to /home/nicolas/Desktop/Nico/eykar/API/node_modules/starknet/dist/account/default.js:125:92

the error is here:
```js
    Account.prototype.getNonce = function () {
        return __awaiter(this, void 0, void 0, function () {
            var result;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, this.callContract({
                            contractAddress: this.address,
                            entrypoint: 'get_nonce',
                        })];
                    case 1:
                        result = (_a.sent()).result;

                        // ------------------------------------------I Added a console.log -----------------------------------------
                        console.log(_a.sent())


                        return [2 /*return*/, (0, number_1.toHex)((0, number_1.toBN)(result[/*     THIS IS THE ERROR        */0]))];
                }
            });
        });
    };
```

So I printed the source of the "result" variable in the console (_a.sent()), and I get this: 

```js
[Object: null prototype] {
  code: 'StarkErrorCode.MALFORMED_REQUEST',
  message: "can't use a string pattern on a bytes-like object"
}
```
So there's definitely something I missed (this is the first time I've done this). If you have an idea of the problem, don't hesitate.
Thank you in advance

**Comment by 0x25cfb68** [comment]
I just faced this issue too, like you did I was able to track it down to `getNonce` ([link](https://github.com/0xs34n/starknet.js/blob/ebe557891922f1e7ed51b7283b90cc60dce0a5d4/src/account/default.ts#L48))

I noticed that this call fails if the address has capital letters:
```js
const { result } = await this.callContract({
  contractAddress: this.address,
  entrypoint: 'get_nonce',
});
```
when I updated my account initialization it worked 

```js
const account = new Account(
   defaultProvider,
   process.env[`ACCOUNT_ADDRESS`].toLowerCase(),
   ec.getKeyPair(import.meta.env[`ACCOUNT_PRIVATE_KEY`])
);
```
the weird thing is I copied the address straight from argent wallet which capitalize some of the address letters

**Comment by 0x25cfb68** [comment]
I just faced this issue too, like you did I was able to track it down to `getNonce` ([link](https://github.com/0xs34n/starknet.js/blob/ebe557891922f1e7ed51b7283b90cc60dce0a5d4/src/account/default.ts#L48))

I noticed that this call fails if the address has capital letters (checksumed):
```js
const { result } = await this.callContract({
  contractAddress: this.address,
  entrypoint: 'get_nonce',
});
```
looks like Starknet fails to make calls to contracts with checksumed address, the weird thing is that executing calls works without needing to lowercase the address 🤔 

when I updated my account initialization it worked 

```js
const account = new Account(
   defaultProvider,
   process.env[`ACCOUNT_ADDRESS`].toLowerCase(),
   ec.getKeyPair(import.meta.env[`ACCOUNT_PRIVATE_KEY`])
);
```
PS: I copied the address straight from Argent wallet without noticing it was checksumed.

**Comment by Marchand-Nicolas** [comment]
What version of starknet js are you using? I get this error now:

**Comment by Marchand-Nicolas** [comment]
Sorry, I missclicked 

Before, the address was written in hexadecimal on my side, and not a string, so I added " " around it. However the .toLowerCase() probably has no effect as the address is written in plain text in my code, and contains no capitals. However, using a string instead of hexadecimal changes the error when I try to invoke the function. I get this now: 

```js
TypeError: keyPair.sign is not a function
    at sign (/home/nicolas/Desktop/Nico/eykar/API/node_modules/starknet/dist/utils/ellipticCurve.js:89:32)
```

**Comment by badurinantun** [comment]
This look like it could be an issue with the way you created and instance of the Account class. Can you share how you did that?

**Comment by Marchand-Nicolas** [comment]
This is how I define the account: 

```js
const address = "0x6806c42960e739918af543b733e76eb4f52a99402ec00e57794cb26cb3a6723"

const account = new starknet.Account(starknet.Provider, address.toLowerCase(), starkKeyPair)


const accountContract = new starknet.Contract(
  compiledArgentAccount.abi,
  address,
  account
);
```

**Comment by Marchand-Nicolas** [comment]
Since the error is from keyPair.sign, it is probably relevant that I show you how I define starkKeyPair : 
```js
const starkKeyPair = JSON.parse(fs.readFileSync("./Account.json").toString("ascii"))
```

**Comment by Marchand-Nicolas** [comment]
Finally, there is one last problem: the transaction is sent, but it is rejected with this error: 

https://alpha4.starknet.io/feeder_gateway/get_transaction_receipt?transactionHash=0x7fc4ebd0e21224d234b1d8990c2666128f5bb7dd4db26d5cbc4c66f52bf1c89

```json
{"status": "REJECTED", "transaction_failure_reason": {"code": "TRANSACTION_FAILED", "error_message": "Error at pc=0:106:\nSignature (2465209890226095910282269659247122656108910640513069997212642860629957127747, 3401469537171587084941523311194111722773524147549488459901284900497655692049), is invalid, with respect to the public key 3562656802514723013026435448630429698527038034468079240529723965178352933348, and the message hash 3611978833539989941168032315577069034184616093335238571336835042812622740617.\nCairo traceback (most recent call last):\nUnknown location (pc=0:844)\nUnknown location (pc=0:769)\nError message: signer signature invalid\nUnknown location (pc=0:1648)"}, "transaction_hash": "0x7fc4ebd0e21224d234b1d8990c2666128f5bb7dd4db26d5cbc4c66f52bf1c89", "l2_to_l1_messages": [], "events": []}
```
It is, I suppose, another signature problem. This is the way to define starkKeyPair : 

```js
const starkKeyPair = ec.genKeyPair()
```
Shouldn't it be generated from my account information? This seems surprising to me. I got this code from the documentation

**Comment by Marchand-Nicolas** [comment]
I solved the problem by changing my account. I used an account generated on ArgentX.
(and the .toLowerCase() helped me with the address given by ArgentX)
