### ISSUE TITLE
Support `get_block_traces`

### ISSUE THREAD

**Issue by badurinantun** [0xs34n/starknet.js#253]
Cairo version v0.9.1 introduces `get_block_traces` endpoint, which given a block identifier, returns the traces of all the transactions within that block.

This should be supported by both `SequencerProvider` and `RpcProvider` from the #243.

I'm not sure if this should be a new method or if the `getBlock` should receive an option to return traces.

**Comment by asaroukou** [comment]
Hi. I'm working on this issue assigned to me from [olydust](https://app.onlydust.xyz/contributions/0x002d)

I'm wondering, how to make all the tests pass since number of methods seems to be unavailable on devnet.

**Comment by ivpavici** [comment]
Hi @asaroukou , you can try with testnet?
But what is the issue you are facing? get_block_traces exists on devnet
