### ISSUE TITLE
How to use Uint256 as an input for contract functions?

### ISSUE THREAD

**Issue by Marchand-Nicolas** [0xs34n/starknet.js#259]
How to use Uint256 as an input for contract functions?

I tried that :

```js
account.execute(
  {
    contractAddress: eykarCommunityContract.address,
    entrypoint: "completeQuest",
    calldata: [5, /* This is the Uint256 : */ [8, 0]],
  },
  undefined,
  { maxFee: "60240850062409" }
);
```
and that :

```js
calldata: [5, { low: 8, high:0 }]
```

but it doesn't seem to work (the transaction is rejected), while it works on voyager with the same inputs and the same user.

Thank you in advance for your answer(s)

**Comment by fracek** [comment]
I ha the same issue when adding a hook for multicalls to starknet-react. I believe there should be a version of `execute` that does argument encoding like contract's `invoke`.

**Comment by Marchand-Nicolas** [comment]
It seems to work. Thank you!

**Comment by caelinsutch** [comment]
Which one was the fix?

**Comment by Marchand-Nicolas** [comment]
I have just finished, here is what there is to know:

When calling a function, use this syntax for Uint256: e.g. [13, 0] 

e.g. `contract.exampleFunction("2", [tokenId, 0])`

But when executing a function, use this syntax: e.g. "13", "0" (do not group the two values in an array)

e.g. 

```js
account.execute(
            {
                contractAddress: eykarCommunityContract.address,
                entrypoint: "completeQuest",
                calldata: [
                    questId,
                    tokenId,
                    "0"
                  ],
            }
```

Tell me if this is not very clear, or if I have misunderstood something
