### ISSUE TITLE
use develop as default branch

### ISSUE THREAD

**Issue by janek26** [0xs34n/starknet.js#26]
Hey Sean!

can we maybe change the default branch to `develop` ?

It'd improve DX as PRs would be created against develop and also improve release automation, as issues do not get closed if a PR fixing it isn't targeting the default branch.

As the documentation lives on a webpage by now, it would still be valid for the main rpm package :-)

**Comment by seanjameshan** [comment]
Re-opening issue: 

Recently we had a release error created by `semantic release` #45 

This error will happen if we merge 2 PR's at once and the first CI run has not finished. 

Wondering if we could make it unable to merge unless all previous CI's are finished. 

If we add more contributors, everyone needs to remember to not merge 2 PR's at once. Unless it will be just Janek and I merging to main, I think we can manage to remember this rule, but still not ideal.

Also, if we forget it, or accidentally merge 2 PR's, then we need to switch the default branch from `develop` back to `main` and back to `develop`. 

I don't know how risky switching the default branch is, but GitHub gives a warning every time I do it so it seems like there are unintended consequences.

I'm thinking of keeping the default branch to `main` for now, and we can merge `develop` into `main` more often.

**Comment by 0xs34n** [comment]
Switched branch back to `develop` @janek26 @MilGard91
