### ISSUE TITLE
How to initiate a transfer, please help me

### ISSUE THREAD

**Issue by leezijie** [0xs34n/starknet.js#275]
`let startkKeyPair = ec.getKeyPair('0x02d00b96090e46d75e6851a2c1f7ff76aed634c75376fda82924e1e31f0afcf7')
    let signer = new Signer(startkKeyPair)
    
    let transactionDetail = {
        nonce: 0,
        walletAddress: toBN('0x751981883821d4e10fc223de22c044366f5f5b5967bc3f0ef9bc840f5c9a875').toString(),
        chainId: StarknetChainId.TESTNET
    }

    let transation = {
        contractAddress: '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7',
        entrypoint: 'transfer',
        calldata: compileCalldata({
            recipient: "0x4df152798516adc073999cbd71a3dff9875ae8e29b19243026efd429c8e0fd1",
            amount: "0x5af3107a4000"
        })
    }

    let signature = await signer.signTransaction([transation], transactionDetail)
    console.log(signature)

    const provider = new Provider({
        sequencer: {
          baseUrl: 'https://alpha4.starknet.io',
          feederGatewayUrl: 'feeder_gateway',
          gatewayUrl: 'gateway',
        }
      })

    let sign0 = toHex(toBN(signature[0]))
    let sign1 = toHex(toBN(signature[1]))

    let value = await provider.callContract({
        contractAddress: "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
        entrypoint: "transfer",
        calldata: compileCalldata({
            recipient: "0x4df152798516adc073999cbd71a3dff9875ae8e29b19243026efd429c8e0fd1",
            amount: "0x5af3107a4000",
            SIGNATURE_: [sign0,sign1]
        })
    })
   
    console.log(value)`

I signed a transaction with the above code and tried to send it.But I couldn't understand the error of it return.

error logs:
` GatewayError: Error at pc=0:104:
0|icp  |   Got an exception while executing a hint.
0|icp  |   Cairo traceback (most recent call last):
0|icp  |   Unknown location (pc=0:1678)
0|icp  |   Unknown location (pc=0:1664)
0|icp  |   
0|icp  |   Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):
0|icp  |   Error at pc=0:1344:
0|icp  |   An ASSERT_EQ instruction failed: 9:3 != 9:5.`

**Comment by mittalhimang** [comment]
I am also facing the same error
