### ISSUE TITLE
How to calculate contract address of starkPubKey ? 

### ISSUE THREAD

**Issue by mthinh** [0xs34n/starknet.js#277]
I have starkPubKey generated from keypair which is also generated from my privateKey, 
How could I calculate the contract address from that starkPubKey ?

**Comment by leezijie** [comment]
You need deploy a account contract

**Comment by ivpavici** [comment]
@mthinh As stated by @leezijie you first deploy an account, check out how this is done in the workshop repository https://github.com/0xs34n/starknet.js-workshop/blob/d1f51b81e724886d66895d27d08e668465631eb5/index.js#L47

**Comment by ivpavici** [comment]
Although, I have to double check if possible in starknet.js, but there should be a way to calculate the address without deploying an account first, similar to https://docs.openzeppelin.com/cli/2.8/deploying-with-create2

**Comment by ivpavici** [comment]
This should be it:
https://github.com/0xs34n/starknet.js/blob/f296554c48873f57eaeb879978ca43920ffbeebc/src/utils/hash.ts#L144

**Comment by mthinh** [comment]
> 
@ivpavici Tks, I have used this function but the output was not the same with the address I receive from `deployContract` response.
I used `contract` and `starkPubkey` as an input of `deployContract`. 
then when I call 
`calculateContractAddressFromHash(starkPubKey, undefined, [], 0)
`
Is this the correct way to calculate address ?

**Comment by mthinh** [comment]
`
export  function calculateContractAddressFromHash(salt: BigNumberish, classHash: BigNumberish, constructorCalldata: RawCalldata, deployerAddress: BigNumberish): string;
`
Are `classHash`  `constructorCalldata` and `deployerAddress` always required ? 
Sr I have no idea and where to get deployerAddress 

Sr I'm really new to blockchain

**Comment by dhruvkelawala** [comment]
Yes. deployerAddress is mostly the `factoryAddress`. You can learn more about Factory Pattern [here](https://betterprogramming.pub/learn-solidity-the-factory-pattern-75d11c3e7d29) .

Having said so, it doesn't HAVE to be a factory contract. If you are deploying a contract, you can just use your account address in deployerAddress.

**Comment by mthinh** [comment]
@dhruvkelawala hmm, I don't really get you here, but let me tell you my context. 
Im working on restoring a deployed account. 
So I have a private key then I get a keypair and publicStarkKey from that private key tks to `ec.getKeyPair(privKey)` and `ec.getStarkKey(keypaird)` . The thing is how can I calculate my account address (the account that I had deployed before) from those two ?
