### ISSUE TITLE
Lets use 2 different (funded) wallets for our tests

### ISSUE THREAD

**Issue by janek26** [0xs34n/starknet.js#280]
Currently the test run for for the sequencer provider and for the rpc provider share the same wallet and keypair for testing provided by `TEST_ACCOUNT_ADDRESS=` and `TEST_ACCOUNT_PRIVATE_KEY=`.

I propose to add a 2nd funded wallet (we need some more funds for the existing wallet too, as it's [almost empty](https://goerli.voyager.online/contract/0x06c0a3ca4f79e978f3b7005898aaa49bef4a24aeaa5f10c6a97887516400197e))

we could rename the secrets into something like:
```
TEST_ACCOUNT_ADDRESS_1=***
TEST_ACCOUNT_PRIVATE_KEY_1=***
TEST_ACCOUNT_ADDRESS_2=***
TEST_ACCOUNT_PRIVATE_KEY_2=***
```

and map it inside the workflow file to the job

This would enable us to run release pipelines in parallel and would speed up the pipeline 3 times

**Comment by 0xs34n** [comment]
We can't run them in parallel in the same wallet because it would cause a nonce issue right?

Would it be wise to name the wallets more explicitly? like 

```
TEST_ACCOUNT_ADDRESS_RPC

& 

TEST_ACCOUNT_ADDRESS_SEQUENCER
```

**Comment by janek26** [comment]
Right, currently we limit the matrix to run maximum 1 job in parallel because otherwise we would get nonce issues
See https://github.com/0xs34n/starknet.js/blob/develop/.github/workflows/release.yml#L29

I opted for more general names to avoid having explicit mapping to sequencer/rpc in the secret name
This mapping would be done in the workflow file

By keeping it this way we can add more/less accounts and just do the mapping in the workflow file, in example if we decide to have multiple test accounts for one kind of provider to parallelise tests further

**Comment by 0xs34n** [comment]
Sounds good. Also, I added 0.015 ETH (max amount on layer swap) to the almost empty wallet.

**Comment by 0xs34n** [comment]
rip

**Comment by 0xs34n** [comment]
funded 0.25 eth in testnet

**Comment by tabaktoni** [comment]
Closing this issue as the Sequencer provider is going to be deprecated, untill than we are going to run on 1 test acc.
