### ISSUE TITLE
Backend signature verification

### ISSUE THREAD

**Issue by wdev11** [0xs34n/starknet.js#281]
Hello,
We're currently trying to implement an authentication workflow using the user's wallet signature.
We've managed to do it in the frontend side, but we're now struggling to implement its verification on the backend side.

Verifying the signature isn't a problem on the frontend since we do have the `account` instance so we can use `account.verifyMessage`. 
How to do it on the backend side though ? Since we do not have the account instance.
We've thought about instanciating a new signer corresponding to the account on the backend and verifying the signature using this one, but we can't instanciate this signer without the account's public key, that we do not manage to get in the frontend, the account's `signer`'s `pubkey` being null.

What are we doing wrong ? How can we fix this ?

Thanks!

**Comment by janek26** [comment]
Hey! Because of account abstraction, signature validation needs to be done onchain!
You can call https://github.com/argentlabs/argent-contracts-starknet/blob/develop/contracts/ArgentAccount.cairo#L486 with the signature from anywhere

**Comment by ivpavici** [comment]
@wdev11 I'm closing this, feel free to reopen if you have any more questions following @janek26's comment

**Comment by gianlukk994** [comment]
Hey! I'm jumping here because I'm stuck implementing the off-chain verification. 
Is it still not possible? 

FYI This link https://github.com/argentlabs/argent-contracts-starknet/blob/develop/contracts/ArgentAccount.cairo#L486 returns 404.

Thanks!

**Comment by Agostin** [comment]
Hey there!
I'm also looking for a solution to this problem: do you please have any news about it? 🙏🏻

@gianlukk994 I guess the correct page that @janek26 was linking is [this](https://github.com/argentlabs/argent-contracts-starknet/blob/develop/contracts/account/ArgentAccount.cairo).

**Comment by ivpavici** [comment]
@Agostin  @gianlukk994  I honestly don't know, but I didn't hear anything change about this in the meantime... so I guess this is how it works (on-chain)

**Comment by gianlukk994** [comment]
@ivpavici Many thanks for your help here and on Discord! 
@Agostin, thanks for the link!
