### ISSUE TITLE
`deployContract` of the `RpcProvider` throws an error

### ISSUE THREAD

**Issue by ivpavici** [0xs34n/starknet.js#285]
From Consensys:

When using the "deployContract" function of the "RpcProvider" class, we always get the following error:

```
Error: -32602: More than 64 digits found: 76 at line 1 column 147
  at RpcProvider.eval (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:18455)), <anonymous>:70169:35)
```

I think the root cause is that inside the function, `constructorCalldata` was converted to decimal string and passed to `starknet_addDeployTransaction`, but they should instead be in hex string...

**Comment by dkillen** [comment]
This looks like a blocker for the Truffle team too. I've encountered the same error in my project attempting to deploy an OZ account contract with the RPC provider. The project that I am currently working on needs to allow the user to choose whether to use an RPC provider or Sequencer provider. Is there any chance this will be fixed soon?

**Comment by janek26** [comment]
@dkillen we’re also happy about every PR!

**Comment by dkillen** [comment]
Hi @ivpavici 

The project I am working on is currently using the OZ Cairo contracts v0.3.1. I am just using the basic Account preset:

```
%lang starknet

from openzeppelin.account.presets.Account import constructor
``` 

I am first instantiating a Provider based on the users config (either rpc or sequencer):

```javascript
let starkNetProvider;
if (network.rpc_url) { // instantiate an RPCProvider
  starkNetProvider = new Provider({
    rpc: {
      nodeUrl: network.rpc_url
    }
  });
} else { // instantiate a SequencerProvider
  starkNetProvider = new Provider({
    sequencer: {
      baseUrl: network.base_url,
      feederGatewayUrl: network.feeder_gateway_url,
      gatewayUrl: network.gateway_url
    }
  })
}
```

The configuration file provides the following:

```javascript
    testnet: {
      network_id: "goerli-alpha",
      rpc_url: "https://starknet-goerli.infura.io/v3/" + infuraApiKey,
      // StarkNet sequencer endpoints.
      // base_url: "https://alpha4.starknet.io",
      // feeder_gateway_url: "feeder_gateway",
      // gateway_url: "gateway",
      block_explorer_url: "https://goerli.voyager.online"
    },
```

Account keys are generated with the following:

```javascript
const accountKeyPair = ec.genKeyPair();
const accountPublicKey = ec.getStarkKey(accountKeyPair);
const accountPrivateKey = `0x${accountKeyPair.getPrivate('hex')}`;
```

Contract is deployed with the following:

```javascript
const callData = [
  accountPublicKey
];
const deployContractResponse = await starkNetProvider.deployContract({
  contract: compiledAccountContract,
  constructorCalldata: callData,
  addressSalt: accountPublicKey
});
```

This pattern works to successfully deploy an account with the sequencer provider. It fails with the following error when using the rpc provider:

```
/Users/david/dev/trufflesuite/boxes/starknet-box/node_modules/starknet/dist/provider/rpc.js:90
                            throw new Error("".concat(code, ": ").concat(message));
                                  ^

Error: -32602: More than 64 digits found: 76 at line 1 column 149
    at RpcProvider.<anonymous> (/Users/david/dev/trufflesuite/boxes/starknet-box/node_modules/starknet/dist/provider/rpc.js:90:35)
    at step (/Users/david/dev/trufflesuite/boxes/starknet-box/node_modules/starknet/dist/provider/rpc.js:33:23)
    at Object.next (/Users/david/dev/trufflesuite/boxes/starknet-box/node_modules/starknet/dist/provider/rpc.js:14:53)
    at fulfilled (/Users/david/dev/trufflesuite/boxes/starknet-box/node_modules/starknet/dist/provider/rpc.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Thanks @janek26 I will take a look into this myself if I can make some time to do so. I have submitted a PR previously, albeit just a minor documentation fix.

**Comment by jonesho** [comment]
@ivpavici just to add more context, for the use case of StarkNet MM snap, our call patten is similar:
`const provider = getProvider(network);
  return provider.deployContract({
    contract,
    constructorCalldata,
    addressSalt,
  });`

I was able to fix this issue locally by changing the rpc.ts line#184 as:
`bigNumberishArrayToHexStringArray`
which is a simple helper function I created similar to the existing "bigNumberishArrayToDecimalStringArray" for turning bignumberish array into hex string array (instead of decimal array)

I guess the reason is that sequencer and rpc are expecting different format for the "constructor_calldata" param: decimal string vs hex string:

**Rpc accepted JSON-RPC payload**:
`{
    "method": "starknet_addDeployTransaction",
    "jsonrpc": "2.0",
    "params": [
        "0x06729eefa66501282721df168b29b8aaf8f7835a38785297960c0c7f722deba2",
        [
            "0x3e327de1c40540b98d05cbcb13552008e36f0ec8d61d46956d2f9752c294328",
            "0x79dc0da7c54b95f10aa182ad0a46400db63156920adb65eca2654c0945a463",
            "0x2",
            "0x6729eefa66501282721df168b29b8aaf8f7835a38785297960c0c7f722deba2",
            "0x0"
        ],
        {...}
    ],
    "id": 0
}`

**Sequencer accepted JSON-RPC payload**:
`{
    "method": "starknet_addDeployTransaction",
    "jsonrpc": "2.0",
    "params": [
        "0x06729eefa66501282721df168b29b8aaf8f7835a38785297960c0c7f722deba2",
        [
            "1758287985645384642592689047925649198321392050007099540447534039060479296296",
            "215307247182100370520050591091822763712463273430149262739280891880522753123",
            "2",
            "2916394593757771767928255068651311427359933061407155439031328000282249259938",
            "0"
        ],
        {...}
    ],
    "id": 0
}`

**Comment by dkillen** [comment]
@jonesho & @ivpavici I came to a similar solution and have submitted a PR to fix this bug.

**Comment by ivpavici** [comment]
Thanks @dkillen and @jonesho ! We have to do some more refactoring and changes regarding RPC and providers in general (mentioned here https://github.com/0xs34n/starknet.js/pull/307), and we will incorporate these changes also!
