### ISSUE TITLE
When I deployed an account on the main network contract error

### ISSUE THREAD

**Issue by leezijie** [0xs34n/starknet.js#287]
`let keyPair = ec.genKeyPair()
    let starkPubKey = ec.getStarkKey(keyPair)
    const starkKeyInt = toBN(encode.removeHexPrefix(starkPubKey), 16);

    const compiledArgentAccount = json.parse(
        fs.readFileSync("./docs/newaccount.json").toString("ascii")
    )
    
    const provider = new Provider({network:'mainnet-alpha'})
    // const provider = new Provider({network:'goerli-alpha'})

    const account = await provider.deployContract({
        contract: compiledArgentAccount,
        constructorCalldata:[starkKeyInt],
        addressSalt: starkPubKey,
    })`

error logs:
The contract class attempted to be deployed is not permitted

But I can deploy in the test network, do I need to apply for any permissions

**Comment by ivpavici** [comment]
Hi!
There's a whitelist of contacts for mainnet. Is this contract you want to deploy some special contract? There's a form you can fill in order to add it for mainnet: https://forms.reform.app/starkware/SN-Alpha-Contract-Deployment/l894lu

**Comment by leezijie** [comment]
Yes, I'm using the account contract code in the demo. I want to deploy it on the main network

**Comment by leezijie** [comment]
> Hi! There's a whitelist of contacts for mainnet. Is this contract you want to deploy some custom contract? There's a form you can fill in order to add it for mainnet: https://forms.reform.app/starkware/SN-Alpha-Contract-Deployment/l894lu

Thanks a lot.
I'm using the account contract code in the demo. I want to deploy it on the main network

**Comment by leezijie** [comment]
> Hi! There's a whitelist of contacts for mainnet. Is this contract you want to deploy some custom contract? There's a form you can fill in order to add it for mainnet: https://forms.reform.app/starkware/SN-Alpha-Contract-Deployment/l894lu

I want to use this contract, but I don't have its source code, do you know its source code.
https://github.com/0xs34n/starknet.js/blob/develop/__mocks__/Account.json

**Comment by ivpavici** [comment]
afaik it is OpenZeppelin account implementation https://github.com/OpenZeppelin/cairo-contracts/tree/main/src/openzeppelin/account/presets
