### ISSUE TITLE
How can I do async transactions ?

### ISSUE THREAD

**Issue by Marchand-Nicolas** [0xs34n/starknet.js#291]
How can I do async transactions ? Because of the nonce, transactions are rejected

**Comment by Marchand-Nicolas** [comment]
Here is how I execute the transaction :
```js
account.execute(
   transaction,
   undefined,
   { maxFee: "200240850062409", nonce: nonce }
 );
```
but the problem is the nonce (the first transaction is accepted, the other are rejected because of the nonce)

**Comment by Marchand-Nicolas** [comment]
Is it possible to count the nonce manually (knowing that the transactions can not be rejected by the contract, that only my account can and does the transaction, and this from a server)

**Comment by Marchand-Nicolas** [comment]
This is how I define the nonce : 
```js
const nonce = account.getNonce();
```

**Comment by tabaktoni** [comment]
What do you mean by async transactions? do you mean like sending bulk transactions ?
Is this still the issue with latest version?

**Comment by Marchand-Nicolas** [comment]
I mean, sending transactions one after the other, without waiting for each transaction to be completed before sending the next. The problem is the nonce. But I don't want to do multicall because I don't want to send the transactions at the same time.

**Comment by janek26** [comment]
why wouldnt you send them all at once?

**Comment by Marchand-Nicolas** [comment]
Because I want to make a transaction every time X event happens, without waiting

**Comment by tabaktoni** [comment]
This is probably not possible because the nonce is incremented by the account by the transaction request.
Regarding further discussion it can be done here with the starkware team:
https://community.starknet.io/t/starknet-account-abstraction-model-part-1/781/16

Closing as it is not issue with starknet js implementation

**Comment by tabaktoni** [comment]
Closing as it is not issue with starknet js implementation
