### ISSUE TITLE
"Method not found" using getBlock with RpcProvider

### ISSUE THREAD

**Issue by envusr** [0xs34n/starknet.js#292]
getBlock throws an error when using it with an RpcProvider

`Error: -32601: Method not found
    at RpcProvider.<anonymous> (/node_modules/starknet/dist/provider/rpc.js:91:35)`

but everything is fine with a default provider

**Comment by ivpavici** [comment]
Hello!
Can you please provide more code, how do you call `getBlock`? Since this method exists... Also, which version of starknet.js are you using?

**Comment by envusr** [comment]
I'm using starknet v4.3.0
here is how I call getBlock:
`import { RpcProvider } from 'starknet';
const providerConfig1 = {
	nodeUrl: url
};
const provider1 = new RpcProvider(providerConfig1);
provider1.getBlock(150000).then(console.log);`
or
`import { Provider } from 'starknet';
const providerConfig2 = {
	rpc: {
		nodeUrl: url
	}
};
const provider2 = new Provider(providerConfig2);
provider2.getBlock(150000).then(console.log);`
same error for both cases
I remember it worked previously, but recently, it stopped (literally from one day to another), maybe the lib changed? but I don't know if it is possible as it is the same version

**Comment by envusr** [comment]
hi, I just found the problem
starknet hasn't been updated for pathfinder v0.3.0
e.g. for getBlock with an rpc provider, starknet tries to call either `starknet_getBlockByHash` or `starknet_getBlockByNm
umber` depending on the type of blockIdentifier (can be a hash or a number), but both methods have been deleted in [v0.3.0 of pathfinder](https://github.com/eqlabs/pathfinder/releases/tag/v0.3.0-alpha)
you should use `starknet_getBlockWithTxs` or `starknet_getBlockWithTxHashes` instead

**Comment by envusr** [comment]
hi, I just found the problem
starknet hasn't been updated for pathfinder v0.3.0
e.g. for getBlock with an rpc provider, starknet tries to call either `starknet_getBlockByHash` or `starknet_getBlockByNumber` depending on the type of blockIdentifier (can be a hash or a number), but both methods have been deleted in [v0.3.0 of pathfinder](https://github.com/eqlabs/pathfinder/releases/tag/v0.3.0-alpha)
you should use `starknet_getBlockWithTxs` or `starknet_getBlockWithTxHashes` instead

**Comment by envusr** [comment]
hi, I just found the problem
starknet hasn't been updated for pathfinder v0.3.0
e.g. for getBlock with an rpc provider, starknet tries to call either `starknet_getBlockByHash` or `starknet_getBlockByNumber` depending on the type of blockIdentifier (can be a hash or a number), but both methods have been deleted in [v0.3.0 of pathfinder](https://github.com/eqlabs/pathfinder/releases/tag/v0.3.0-alpha)
you should use `starknet_getBlockWithTxHashes` instead

**Comment by envusr** [comment]
hi, I just found the problem
starknet hasn't been updated for pathfinder v0.3.0
e.g. for getBlock with an rpc provider, starknet tries to call either `starknet_getBlockByHash` or `starknet_getBlockByNumber` depending on the type of blockIdentifier (can be a hash or a number), but both methods have been deleted in [v0.3.0 of pathfinder](https://github.com/eqlabs/pathfinder/releases/tag/v0.3.0-alpha)
you should use `starknet_getBlockWithTxHashes` instead
same problem for getCode and getTransactionCount
