### ISSUE TITLE
Why I got this errorCode: 'StarknetErrorCode.NON_PERMITTED_CONTRACT' ? 

### ISSUE THREAD

**Issue by mthinh** [0xs34n/starknet.js#294]
I'm learning blockchain and trying to run these code
`
const payload = {
    contract: {
      abi: ProxyContract.abi,
      program: ProxyContract.program,
      entry_points_by_type: ProxyContract.entry_points_by_type,
    },
    constructorCalldata: stark.compileCalldata({
      implementation: accountClassHash,
      entry_point_selector: selector,
      calldata: stark.compileCalldata({
        signer: starkKeyPub,
        guardian: '0',
      }),
    }),
    addressSalt: starkKeyPub,
  };
  const txResponse = await provider.deployContract(payload);
`
Which I cloned for argent-x. It works fine with `goerli-testnet`. But when I switch to `mainnet`, I got this error. Is there any privacy here prevent other user to create an account out of argent-x extension ?

**Comment by ivpavici** [comment]
Hi!
In general, there's a whitelist of contacts for mainnet. There's a form you can fill in order to add it for mainnet: https://forms.reform.app/starkware/SN-Alpha-Contract-Deployment/l894lu

But regardless, this is not a starknet.js issue. Best to maybe ask in discord on the argent-x channel!
