### ISSUE TITLE
Signing an execute transaction with multicall

### ISSUE THREAD

**Issue by a35026** [0xs34n/starknet.js#299]
I'm trying to implement a multicall on the frontend
```ts
const acc = new Account(
  new Provider(),
  account?.address,
  account?.signer
);
const nonce = await acc.getNonce();
const result = await acc.execute(
  [
    {
      contractAddress:
        "0x088888284bf0dce7811aea8950eab7c39c22f2594cef7124366aa93edbcc6b8e",
      entrypoint: "mint",
      calldata: [account?.address, 1, 2, 0, 1, 77, 0],
    },
  ],
  undefined,
  { maxFee: 500, nonce }
);
```
This doesn't invoke Argent X popup window for signing
But passes through and gives me a tx hash with rejected status:
```
Error message: signer signature invalid
```
How can I sign this transaction on the frontend?

**Comment by tabaktoni** [comment]
I don't think we do any integration in starknet.js directly with any wallet interface, as so no wallet interface will pop up.
Starknet.js is a low-level JS SDK to communicate with the Starknet network.
ArgentX has some daap examples on the repo that you can check out.

Did you resolve your issue in meantime, or would you need additional guidelines?

**Comment by kongtaoxing** [comment]
Hey there, if you want to use Argent X to execute transaction, you could use following code, but make sure you have Argent X installed and be active:

```javascript
import { stark, Contract} from "starknet";

 await starknet.enable();
const starknet = window.starknet;
const signer = starknet.account;
const callContract = new Contract(abi, contractAddress, signer);
const callTx = await signer.execute(
      {
        contractAddress: contractAddress,
        entrypoint: "mint", 
        calldata: [accountAddress, 1, 2, 0, 1, 77, 0]
      }
    );
```
Then you will see argentX pop up.

**Comment by tabaktoni** [comment]
Help Considered resolved with example.
