### ISSUE TITLE
Implement getContractAddress()

### ISSUE THREAD

**Issue by janek26** [0xs34n/starknet.js#32]
As contract addresses are now deterministic with StarkNet Alpha3 (#29) lets implement a method to calculate the contract address given the deployment transaction details

Reference in python:
https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/services/api/gateway/contract_address.py

**Comment by janek26** [comment]
on it

**Comment by janek26** [comment]
I'll move this back to "todo" as it seems our Peterson hash function is far to slow (8h/s) to archive that. I'd rather wait for stark ware to provide an implementation.
fyi @bbrandtom

**Comment by janek26** [comment]
this is way easier now:
https://medium.com/starkware/alpha-4-6b572072d80b#53c5

**Comment by dhruvkelawala** [comment]
Waiting for this to be implemented. Is there anyway I could help by creating a PR?

**Comment by janek26** [comment]
[CONTRACT HASH](https://starknet.io/documentation/contracts/#contract_hash) may be part of the compiled JSON in the coming version, which would enable this feature as described here: https://starknet.io/documentation/contracts/#contracts_addresses

I guess it could be implemented today, but you would need to calculate the contract hash yourself as described

**Comment by dhruvkelawala** [comment]
`starknet.py` implemented it 4 days ago. They are also calculating the hash themselves I guess. I think we can implement it. But any issue that I should keep in mind?

**Comment by janek26** [comment]
> I'll move this back to "todo" as it seems our Peterson hash function is far to slow (8h/s) to archive that. I'd rather wait for stark ware to provide an implementation.
> 
> fyi @bbrandtom @starkware-libs

Maybe just that the hash function is very slow right now in JS, which makes contract hash calculations very long. 
So we should switch to the precomputed value when available, and maybe fallback to the calculations which can be implemented today 🙂

**Comment by yogh333** [comment]
Hi, 

 Nowadays, contract addresses seem to be computed and returned by the sequencer ([here](https://github.com/0xs34n/starknet.js/blob/develop/src/provider/default.ts#L340)). I am wondering how the `caller address` is provided to the sequencer ? Is it through the `DeployContractPayload` where both salt and caller address are passed through the `addressSalt` field ?

**Comment by janek26** [comment]
`caller address` for contract deployment is always `0` currently 👍

**Comment by janek26** [comment]
implemented

**Comment by dhruvkelawala** [comment]
As a memoir to myself, we now compute class hash in starknet.js with #399
