### ISSUE TITLE
Declare contract returns error

### ISSUE THREAD

**Issue by Shinwari536** [0xs34n/starknet.js#328]
`Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"code": "StarknetErrorCode.ENTRY_POINT_NOT_FOUND_IN_CONTRACT", "message": "Entry point 0x289da278a8dc833409cabfdad1581e8e7d40e42dcaed693fa4008dcdb4963b3 not found in contract with class hash 0x6a2c4510a0eb1bbcb75b66b23b9f3897c43644b1c86c2547cbe708f97c8f18b."}
`

Getting the following error when declaring  the AMM compiled code [here](https://www.cairo-lang.org/docs/hello_starknet/intro.html#your-first-contract)
using following command
`starknet declare --contract contract_compiled.json`

**Comment by ivpavici** [comment]
Hello! 
This is not related to the starknet.js library as far as I can see (I guess you are following this tutorial https://starknet.io/docs/hello_starknet/intro.html)! Please seek help on discord!

**Comment by Shinwari536** [comment]
@ivpavici I am unable to join starknet discord. Can you please in this regard. Yes, I am following the same link tutorial you shared.
