### ISSUE TITLE
Implement getTransactionHash()

### ISSUE THREAD

**Issue by janek26** [0xs34n/starknet.js#33]
Also transaction hashes are now deterministic with StarkNet Alpha3 (#29) lets implement a method to calculate the transaction hash given the transaction details

Reference in python:
https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/services/api/gateway/transaction_hash.py

(not as important, and maybe depending on #32

**Comment by dan-ziv** [comment]
@janek26 
I already did it in our bridge (StarkWare). 
TAL here:
https://github.com/starkware-libs/starknet-bridge/blob/dev/src/utils/hash.js#L6

The only thing that is actually missing is to calculate dynamically the tx hash prefixes from the chain ID and the transaction ID.
In `python` it's been done by `b` function and then `from_bytes` function. From my searches, I didn't find something equal in Javascript that gave me the same outputs.
For now, I'm saving it hard-coded here:
https://github.com/starkware-libs/starknet-bridge/blob/dev/src/enums/ChainType.js#L9
https://github.com/starkware-libs/starknet-bridge/blob/dev/src/enums/ChainType.js#L17
https://github.com/starkware-libs/starknet-bridge/blob/dev/src/constants.js#L5

**Comment by janek26** [comment]
Hey Dan, 
I think https://github.com/seanjameshan/starknet.js/blob/main/src/utils/shortString.ts is what you are looking for. It returns the same as b from python afaik

**Comment by janek26** [comment]
solved in #166
