### ISSUE TITLE
simulate_transaction

### ISSUE THREAD

**Issue by tabaktoni** [0xs34n/starknet.js#338]
Sequencer:
simulate_transaction - Simulates the transaction and returns the transaction trace and estimated fee (see [here](https://www.starknet.io/docs/0.10.0/hello_starknet/cli.html#simulate-transaction))

Like estimateFee but with different response.

**Comment by ivpavici** [comment]
#339 and #340 should probably be dealt with first, and then this issue

**Comment by ivpavici** [comment]
https://www.starknet.io/docs/0.10.0/hello_starknet/cli.html#simulate-transaction
