### ISSUE TITLE
Update tests to use Json Object Schemas for validation

### ISSUE THREAD

**Issue by tabaktoni** [0xs34n/starknet.js#344]

**Comment by tabaktoni** [comment]
When testing response or request object in jest, instead of checking property by property validate it against the defined json schema.

Example:
instead of doing this
```ts
       expect(res).toHaveProperty('contractAddress');
       expect(res).toHaveProperty('entrypoint');
       expect(res).toHaveProperty('calldata');
```
define schemas so we can do it like this:
```ts
expect(res).toMatchSchema(schema);
```

Steps to implement:
1. add json schema package like (https://www.npmjs.com/package/jest-json-schema)
2. go true tests and create json schemas where required ( like objects with multiple props 3+)
3. implement schema into test

**Comment by irisdv** [comment]
I'm interested to work on this issue
