### ISSUE TITLE
Support for getClass and getClassHashAt

### ISSUE THREAD

**Issue by broody** [0xs34n/starknet.js#350]
Hello, currently Starknetjs only supports `getClassAt`, would be great to also have `getClass` and `getClassHashAt`. I can submit a PR to add these. Thanks

**Comment by ivpavici** [comment]
Hello, which starknet.js version are you using?

We support all the methods you mentioned in the RPC provider

**Comment by tabaktoni** [comment]
Try to use starknet@next or 4.7.0.
You could create PR updating project documentation.
Thanks for feedback.

**Comment by broody** [comment]
Ahh got it, completely missed that. Thanks! Happy to update the doc
