### ISSUE TITLE
GetTransaction and/or GetTransactionReceipt should return the block_hash and block_number of accepted transactions

### ISSUE THREAD

**Issue by wraitii** [0xs34n/starknet.js#352]
There are currently no functions in Starknet.js's Provider class to get the block hash/block number of a successful transaction.
However, the feeder gateway (and I suspect RPC endpoints) do provide that information in both `GetTransaction` and `GetTransactionReceipt` endpoints.

This is true of Starknet.js 3.19 and of latest development version as far as I can tell.

The simplest solution would be to update relevant provider to forward that data. I'm not sure which functions is better suited.

**Comment by tabaktoni** [comment]
After testing it seems that Sequencer and Sequencer over Provider both return block_hash and block_number.
But for RPC and RPC over Provider both don't.
Thank you @wraitii for reporting, this will be fixed.
