### ISSUE TITLE
new Contract() address no longer optional

### ISSUE THREAD

**Issue by archseer** [0xs34n/starknet.js#359]
Since the 0.10 support PR, `toLowerCase()` is called on `address` which blows up if address isn't defined. It's marked as optional in the documentation.

https://github.com/0xs34n/starknet.js/blob/0f685efbf0c39b80329db77fda5e1d0dfc4177e0/src/contract/default.ts#L116-L129

**Comment by tabaktoni** [comment]
Thank you for reporting
