### ISSUE TITLE
Guides

### ISSUE THREAD

**Issue by 0xs34n** [0xs34n/starknet.js#36]
End-to-end and comprehensive guides on how to use StarkNet.js

**Comment by seanjameshan** [comment]
Added a bit more documentation on the README for the ZigZag team to start using starknet.js - more to come as demand for this library grows.

**Comment by cwkang1998** [comment]
would love to help on this, any specific docs that you would like to see added?

**Comment by ivpavici** [comment]
Hi @cwkang1998 , thanks for reaching out! Anything you think of will be helpful, but I can write here when I get some ideas. For example I have a plan to write a guide about how to run local tests when changing starknet.js code, hope to do it next week

**Comment by tabaktoni** [comment]
- There are shortString in Utils undocumented and maybe some other Utils methods also.
- RPC docs need to be updated (check one by one method)

**Comment by danikula** [comment]
Documentation doesn't describe how to get account's balance. Could anybody help with it?

**Comment by ivpavici** [comment]
@danikula check the newly published guides!

**Comment by PhilippeR26** [comment]
Available for guide update.
