### ISSUE TITLE
How to deploy an account contract？

### ISSUE THREAD

**Issue by 17621859515** [0xs34n/starknet.js#371]
I followed the tutorial to deploy the account contract and got the following failed transaction.
I don't know where is the error.

https://testnet.starkscan.co/tx/0x57857b0662751e9dee00be7940caa8d1cabdbeca46c38b662aa50a3401d63df
![image](https://user-images.githubusercontent.com/69946784/197677413-3656ff92-c8ac-4606-bf0c-3487c7917587.png)

**Comment by tabaktoni** [comment]
What version of starknetjs do you use?
I believe you are missing at least nonce for the details parameter and in payload classHash.

I recommend you to go true Account using - deployAccount

**Comment by 17621859515** [comment]
> What version of starknetjs do you use? I believe you are missing at least nonce for the details parameter and in payload classHash.
> 
> I recommend you to go true Account using - deployAccount

![image](https://user-images.githubusercontent.com/69946784/197725664-53192241-0ec3-4baa-b4ff-6c90b279dc31.png)
"starknet": "^4.9.0"

I don't understand what you mean, I don't know how to do it.
I just want to generate the staknet address correctly for transfers and balance inquiries.

**Comment by ivpavici** [comment]
See updated guides https://www.starknetjs.com/guides/account
