### ISSUE TITLE
Found issue from ts-custom-error on v3.2.0

### ISSUE THREAD

**Issue by Nathan-SL** [0xs34n/starknet.js#372]
Encountered an issue when using lib `"ts-custom-error": "^3.2.0",`
```ts
node_modules/ts-custom-error/dist/custom-error.d.ts:3:45 - error TS2304: Cannot find name 'ErrorOptions'.
```
Here's a fix suggested to set it at "3.2.2"  https://github.com/adriengibrat/ts-custom-error/issues/81

**Comment by adriengibrat** [comment]
Sorry about that :/ v3.3.1 should build and offer compatibility with Error cause https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#rethrowing_an_error_with_a_cause
