### ISSUE TITLE
Missing Option Token from Sequencer

### ISSUE THREAD

**Issue by tabaktoni** [0xs34n/starknet.js#374]
**Sequencer**
endpoint add_transaction has a second optional parameter token that would create endpoint requests like:
```
/add_transaction?token={token}
```
https://github.com/starkware-libs/cairo-lang/blob/0ba3ff59c1c86f2a30adc8fd144eaacb22c48ce9/src/starkware/starknet/services/api/gateway/gateway_client.py#L14

**RPC**
It seems to me that RPC does not have such an option

How to Resolve:
Add missing token parameter to Sequencer Provider add_transaction using methods

**Comment by irisdv** [comment]
Can work on this one

**Comment by tabaktoni** [comment]
Sort out do we need this to be implemented for mainet. As deploy go true Acc (UDC) and declare also. Is the whitelist token deprecated?

**Comment by ivpavici** [comment]
Confirmed by StarkWare that this is obsolete now!
