### ISSUE TITLE
Support estimate_fee_bulk API 

### ISSUE THREAD

**Issue by ivpavici** [0xs34n/starknet.js#388]
Support estimate_fee_bulk API that computes the fee of multiple transactions that will be executed consecutively

It came out with cairo 0.10.2 

https://github.com/starkware-libs/cairo-lang/blob/f951a669e264796d53bf7a3cfd23d5bc1f6e54b8/src/starkware/starknet/services/api/feeder_gateway/feeder_gateway_client.py#L68

**Comment by yoga-braavos** [comment]
@ivpavici , would be great to address https://github.com/0xs34n/starknet.js/issues/391 as part of this..
