### ISSUE TITLE
Estimate fee does not use feeTransactionVersion

### ISSUE THREAD

**Issue by yoga-braavos** [0xs34n/starknet.js#391]
The `estimate*Fee` functions (e.g. `estimateInvokeFee`) at `src/account/default.ts` use `transactionVersion` instead of `feeTransactionVersion`. for instance: [here](https://github.com/0xs34n/starknet.js/blob/feec75e5cef3c71ae9a751ba521f101a154f2af6/src/account/default.ts#L66)

This is inconsistent with `cairo-lang` behavior and does not allow differentiation between "querying" the contract via the `estimate_fee` endpoint and actually changing its state via `add_transaction`.

**Comment by janek26** [comment]
good catch! PR appreciated

**Comment by yoga-braavos** [comment]
> good catch! PR appreciated

@janek26 see #395

**Comment by yoga-braavos** [comment]
@dhruvkelawala it works because 'estimate_fee' endpoint does not limit calls using transaction version 1 (or 0) but 'add_transaction' does limit transactions to be either 0 or 1 (i.e. non estimate fee transaction version)

There was an issue with OZ contract that asserted on txn version = 1 which caused it to fail. It was fixed in this PR there: https://github.com/OpenZeppelin/cairo-contracts/pull/486

in 'cairo-lang' search for QUERY_VERSION to follow the transaction simulation flow.
