### ISSUE TITLE
Inconsistent `chainId` handling

### ISSUE THREAD

**Issue by delaaxe** [0xs34n/starknet.js#401]
When reading a provider's `chainId` you get a hex value:
```typescript
await provider.getChainId() // returns "0x534e5f4d41494e"
```

But to instantiate a provider you need to pass a chain name:
```typescript
new Provider({ sequencer: { network: "mainnet-alpha" | "goerli-alpha" } })
```

Is it possible to create providers with the hex value or is this due to some difference between sequencer nodes and Pathfinder ndoes?

**Comment by tabaktoni** [comment]
> Is it possible to create providers with the hex value or is this due to some difference between sequencer nodes and Pathfinder nodes?

You can create providers in multiple ways. One you are describing is to create SequencerProvider which has nothing to do with Pathfinder nodes.

We could extend it by enabling SequencerProvider using chainId also.
```
new Provider({ sequencer: { chainId: "0x534e5f4d41494e"} })
```
Is this what you are proposing?
Can you elaborate use-case for this?

Thank you for your feedback
