### ISSUE TITLE
replace functions `@ethersproject/bytes`

### ISSUE THREAD

**Issue by ivpavici** [0xs34n/starknet.js#405]
Replace most of our utils functions, like: 

- @ethersproject/bytes 

...by using the audited `noble` and `scure` packages by https://github.com/paulmillr (base64, utils like utf8tohex etc) **that are potentially not covered through** https://github.com/0xs34n/starknet.js/issues/407

**Comment by irisdv** [comment]
I'm interested to work on this issue
