### ISSUE TITLE
BlockIdentifier is not properly passed to contract call

### ISSUE THREAD

**Issue by lazarmitic** [0xs34n/starknet.js#419]
Even if I set blockIdentifier in options argument to be 'latest', Starknet.js still sends requests using 'pending' block.

I checked the code and it seems the problem is in `buildCall` function. It takes all arguments as array, and calls `contract.call()` without setting the 3rd argument which is the block identifier.

Code in question:
1. buildCall -> contract/default.ts -> line: 37
2. Invalid contract.call() invocation -> contracts/default.ts -> line 39

**Comment by lazarmitic** [comment]
I created PR for this https://github.com/0xs34n/starknet.js/pull/420

**Comment by tabaktoni** [comment]
Resolved with https://github.com/0xs34n/starknet.js/pull/420
