### ISSUE TITLE
Update types

### ISSUE THREAD

**Issue by penovicp** [0xs34n/starknet.js#428]
The sequencer and default provider types have become outdated and should be updated.

**Comment by janek26** [comment]
what do you mean exactly?

**Comment by penovicp** [comment]
To reuse the example from the Slack thread that prompted this issue: because of the `GetTransactionReceiptResponse` typing the `getTransactionReceipt` response sometimes needs to be cast to use the `events` property even though it is always available for both [RPC](https://github.com/starkware-libs/starknet-specs/blob/v0.2.1/api/starknet_api_openrpc.json#L1490) and [sequencer](https://github.com/starkware-libs/cairo-lang/blob/v0.10.2/src/starkware/starknet/services/api/feeder_gateway/response_objects.py#L573). So this issue aims to resolve such desyncs.
