### ISSUE TITLE
UDC deploy function should return the deployed contract address

### ISSUE THREAD

**Issue by bluecco** [0xs34n/starknet.js#442]
**Is your feature request related to a problem? Please describe.**
UDC deploy function is returning only the transaction_hash, also the deployed contract address should be returned

**Describe the solution you'd like**
`deploy` function (in /src/account/default.ts) should return the account address
Instead of having an `InvokeFunctionResponse` it should be a new interface that extends this one

```javascript
export interface DeclareContractResponse extends  InvokeFunctionResponse {
  contract_address: string;
}
```

**Comment by tabaktoni** [comment]
You can use account.deployContract for it.

Does it solve your issue?

**Comment by tabaktoni** [comment]
You can also use account.declareDeploy if you want to declare and deploy the contract.

**Comment by bluecco** [comment]
We can't use it since `account.deployContract` will wait for the transaction

```javascript
 const txReceipt = await this.waitForTransaction(deployTx.transaction_hash, ['ACCEPTED_ON_L2']);
```

The address could be pre-calculated in the `account.deploy` function.

`declareDeploy` function is not working for our purpose at the moment (we need to use `declare` and `deploy` separately)

**Comment by ivpavici** [comment]
Could this help as a workaround:
https://github.com/0xs34n/starknet.js-workshop/blob/main/deploy_erc20.js#L99

**Comment by bluecco** [comment]
I think it would be just better to have it in the deploy function (since developers will also use that function) and we could just use the `deploy` method :)

also, the `parseUDCEvent` has this comment:
```// NOTE: parseUDCEvent will be redundant with nevwer starknet.js version```

**Comment by tabaktoni** [comment]
It can't be inside deployed because than deploy also need to do wait for transaction

**Comment by ivpavici** [comment]
@bluecco yeah, I meant redundant in that workshop since I meant to remove it for the `deployAccount` :D

**Comment by bluecco** [comment]
@tabaktoni but couldn't it be precalculated using `calculateContractAddressFromHash` in the `deploy` function and returned?

so the developer wouldn't need to do that manually or contacting the sequencer and get the transaction. this would avoid a unnecessary network request (since sequencer also has an hard cap for connections)

@ivpavici gotcha, it was a little confusing 😅

**Comment by dhruvkelawala** [comment]
I agree to @bluecco's suggestion. We should return `contract_address` field as a precalculated contractAddress instead of fetching from sequencer.

**Comment by tabaktoni** [comment]
So as Janek also agrees on this one we should do it.
