### ISSUE TITLE
Refactor async Signer

### ISSUE THREAD

**Issue by tabaktoni** [0xs34n/starknet.js#462]
**Describe the bug**
Remove async from all non-async functions
signTransaction should not be async, Abi is not used so it should be removed as an optional parameter and removed validation on it?
Check the rest...

**To Reproduce**
This is Architectural Bug

**Expected behavior**
Same as before but not async for non-await functions

- StarkNet.js version: Latest

**Comment by janek26** [comment]
this is not a bug or anything

The Signer interface should be async, as this allows for much more implementations than having it sync.
Think walletconnect as an example. Remote signers are far more popular than sync signers

**Comment by tabaktoni** [comment]
Oh I see, I was looking into default implementation and it has no sense to me
