### ISSUE TITLE
Refactor Providers transaction/estimates versions

### ISSUE THREAD

**Issue by tabaktoni** [0xs34n/starknet.js#465]
**Describe the refactor**
Providers implement only one version of transaction/estimate but accept the parameter version which is the transaction modifier.
There are two solutions to this:

1.  Refactor provider code so that it supports all versions of transactions:

- Extract the creation of transactions into factory functions for each version of the transaction
- Implement factory function in provider for submitting transactions based on version

2.  Remove the version parameter and fix the value to the supported one (it should be transactionVersion -> 1)

- move transactionVersion to constants
- use transactionVersion as a fixed version in providers

**Comment by dhruvkelawala** [comment]
My suggestion:

- Remove Support for Transaction Version 0
- Only support Transaction Version 1 and 2 for Declare. Declare v1 should be removed in future.

**Comment by tabaktoni** [comment]
Partially resolved.
Not resolved part of the estimate fee version but it has no solution.
