### ISSUE TITLE
Exported `stark.compileCalldata` different from `CheckCallData.compileCalldata`

### ISSUE THREAD

**Issue by JaniAnttonen** [0xs34n/starknet.js#467]
(Using version 4.17.1): Due to the currently exported `stark.compileCalldata` being different from `CheckCallData.compileCalldata` that gets used in the ContractFactory, deploying contracts using `ContractFactory.deploy` does not work as expected (in some cases).

**To Reproduce**
For us the error is given by running deploy using a ContractFactory with an ABI with a constructor that has the inputs `[{ name: 'signers_len', type: 'felt' }, { name: 'signers', type: 'felt*' }, { name: 'threshold', type: 'felt' }]` and passing the resulting `ContractFactory.deploy` the inputs
```
[
    "1",
    "1",
    "230113552613436439708946390704573322871127834961974877288439088301956112268",
    "1"
]
```
that were acquired by
```
stark.compileCalldata({
    "signers_len": "1",
    "signers": [
        "0x823d5a0c0eefdc9a6a1cb0e064079a6284f3b26566b677a32c71bbe7bf9f8c"
    ],
    "threshold": "1"
})
```

**Expected behavior**
Compiling calldata with `stark.compileCalldata` should result in the same calldata than `CheckCallData.compileCalldata` and pass validation when deploying a contract with a contract factory.

**Desktop (please complete the following information):**

- Brave & Chrome
- Node version 18.12.1
- StarkNet.js version 4.17.1
- Network Goerli testnet 1

**Comment by NIC619** [comment]
I think the problem stems from that `stark.compileCalldata` actually handles the array length for you so when using `stark.compileCalldata` you should not need to pass in value for params like `XXX_len`:

```javascript
stark.compileCalldata({
    "signers": [
        "0x823d5a0c0eefdc9a6a1cb0e064079a6284f3b26566b677a32c71bbe7bf9f8c"
    ],
    "threshold": "1"
})
```

I feel like this is not intuitive at all. When people need to encode call data for the first time, they won't know that the length of an array is taken cared of by the function.

**Comment by JaniAnttonen** [comment]
Nope, that does not fix the bug I'm having, but yes, it seems that `stark.compileCalldata` compiles the array length. The problem comes from the mismatch between input types – getting the error `Error: arg signers should be an Array` with signers_len and without. Problem is that the ContractFactory is checking the inputs against the ABI and trying to recompile them, even though they're already compiled and thus, all arrays are flattened.

**Comment by tabaktoni** [comment]
I'm working on refactoring callData and contract interaction in general, and soon we will have a clean solution where you could also use compiled call data for all contract methods interactions and also use them directly as method parameters.

For the latest version in your case at the moment solution will be not to use compileCallData.
```ts
    const factory = new ContractFactory(compiledContract, classHash, account);
    
    const myContract = await factory.deploy([
      ['0x823d5a0c0eefdc9a6a1cb0e064079a6284f3b26566b677a32c71bbe7bf9f8c'],
      1,
    ]);
```

**Comment by JaniAnttonen** [comment]
Thanks for the suggestion, I think it _did_ fix this bug. :)
