### ISSUE TITLE
Class hash of deployed contract different from class hash of compiled one

### ISSUE THREAD

**Issue by NIC619** [0xs34n/starknet.js#473]
**Describe the bug**
I get class hash `A` from compiled contract `Contract` using starknet hardhat plugin but when declaring with starknet.js account, the declare transaction returns class hash `B` for the same contract. Therefore the declare transaction fails because signing payload is not the expected one (because expected class hash `B` is different from input class hash `A`).

**To Reproduce**

1. Example `Contract.cairo` contract used:
```cairo
// Declare this file as a StarkNet contract.
%lang starknet

from starkware.cairo.common.cairo_builtins import HashBuiltin

// Define a storage variable.
@storage_var
func balance() -> (res: felt) {
}

// Increases the balance by the given amount.
@external
func increase_balance{
    syscall_ptr: felt*,
    pedersen_ptr: HashBuiltin*,
    range_check_ptr,
}(amount: felt) {
    let (res) = balance.read();
    balance.write(res + amount);
    return ();
}

// Returns the current balance.
@view
func get_balance{
    syscall_ptr: felt*,
    pedersen_ptr: HashBuiltin*,
    range_check_ptr,
}() -> (res: felt) {
    let (res) = balance.read();
    return (res=res);
}
```

2. Compile the contract and read the contract artifact using starknet hardhat plugin:

```typescript
import { starknet, starknetWrapper } from "hardhat"
import { Account } from "starknet"

const contractFactory = await starknet.getContractFactory("Contract")
const compiledContract = require(contractFactory.metadataPath)
const classHash = await starknetWrapper.getClassHash(contractFactory.metadataPath)
console.log(classHash) // 0x37a54ffa21547ffaef9b75dc2a65d4c0e1f23f3dc2f523fb95df578e12a4293

const account = new Account(provider, ...)
const { transaction_hash, class_hash } = await account.declare({classHash, , contract: compiledContract})
console.log(class_hash) // 0x7c69ad1a294c331b4f99320d992af0f223c93853adce500ea9977668c47075e

await provider.waitForTransaction(transaction_hash) // Error: REJECTED: TRANSACTION_FAILED
// Signature (...) , is invalid, with respect to the public key ..., and the message hash ...
```

The returned class hash from `account.declare(...)` is different from the one derived by `starknetWrapper.getClassHash(...)`.

If it is declared by a starknet hardhat plugin account, it will succeed and return the same class hash as `starknetWrapper.getClassHash(...)`:
```typescript
const defaultAccount = (await starknet.devnet.getPredeployedAccounts())[0]

const class_hash = await defaultAccount.declare(contractFactory)
console.log(class_hash) // 0x37a54ffa21547ffaef9b75dc2a65d4c0e1f23f3dc2f523fb95df578e12a4293
```

I'm not sure if this is the expected behavior but there should only be one class hash for a given contract?

**Expected behavior**

The class hash returned from (starknet.js) `account.declare()` should be the same as (starknet hardhat plugins) `account.declare()` or `starknetWrapper.getClassHash()`.

**Desktop (please complete the following information):**

- Node version: v16.17.0
- StarkNet.js version: 4.17.1
- Network: devnet 0.4.3

**Comment by NIC619** [comment]
Since I get the class hash for comparison using starknet hardhat plugin, it could be that the class hash computed by starknet hardhat plugin is wrong. If this could be the case, I will also open an issue there.

**Comment by NIC619** [comment]
Since starknet hardhat plugin also [proxy the `get_class_hash` call](https://github.com/Shard-Labs/starknet-hardhat-plugin/blob/8caacde1d6a3e89f928e765963ffad33e5557c82/src/starknet-wrappers.ts#L409) to sequencer (devnet), does this mean that the sequencer is computing different class hash for calls from starknet.js and starknet hardhat plugin?

**Comment by NIC619** [comment]
If class hash for starknet.js account declare is fixed and let the declare transaction succeed, meaning declare a different class hash for the same transaction.

```typescript
import { Account } from "starknet"

// declare using starknet.js account
const account = new Account(provider, ...)

// Fix the class hash so the declare transaction will succeed
const { transaction_hash, class_hash } = await account.declare({classHash: "0x7c69ad1a294c331b4f99320d992af0f223c93853adce500ea9977668c47075e", , contract: compiledContract})

await provider.waitForTransaction(transaction_hash) // transaction succeed
```

But then deploy the contract using starknet hardhat plugin, will should fail because it is expecting a different class hash to be declared:
```typescript
const defaultAccount = (await starknet.devnet.getPredeployedAccounts())[0]

const contract = await defaultAccount.deploy(contractFactory)
// This deploy transaction will succeed!
```

However the deploy transaction succeed, meaning that the actual declared class hash is the one computed by starknet hardhat plugin (`0x37a54ffa21547ffaef9b75dc2a65d4c0e1f23f3dc2f523fb95df578e12a4293`)?

**Comment by NIC619** [comment]
OK I think I found why... you can not simply use `require(PATH_TO_COMPILED_CAIRO_CONTRACT_JSON_FILE)`, you have to import `json` from `starknet` and use it to parse the compiled cairo contract json files...

```typescript
import { starknet, starknetWrapper } from "hardhat"
import { Account, json } from "starknet"

const contractFactory = await starknet.getContractFactory("Contract")
const compiledContract = require(contractFactory.metadataPath) // ❌ This don't work
const compiledContract = json.parse(fs.readFileSync(contractFactory.metadataPath).toString('ascii')) // ✅ You have to do this
const classHash = await starknetWrapper.getClassHash(contractFactory.metadataPath)
console.log(classHash) // 0x37a54ffa21547ffaef9b75dc2a65d4c0e1f23f3dc2f523fb95df578e12a4293

const account = new Account(provider, ...)
const { transaction_hash, class_hash } = await account.declare({classHash, , contract: compiledContract})
console.log(class_hash) // 0x37a54ffa21547ffaef9b75dc2a65d4c0e1f23f3dc2f523fb95df578e12a4293

await provider.waitForTransaction(transaction_hash) // Transaction succeed
```

**Comment by NIC619** [comment]
This is not intuitive in my opinion... that I have to parse a (compiled cairo contract) json file in specific way. Is it possible to pass in `PATH_TO_COMPILED_CAIRO_CONTRACT_JSON_FILE` instead of a parsed json object (just like starknet hardhat plugin)?

**Comment by ivpavici** [comment]
@NIC619 thanks, we will clarify in the docs the current situation at least

**Comment by ivpavici** [comment]
Added about ` json.parse` in docs in couple of places
