### ISSUE TITLE
getNonceForAddress is not worked

### ISSUE THREAD

**Issue by ChiHaoLu** [0xs34n/starknet.js#476]
**Describe the bug**
The provider function of `getNonceForAddress()` is not worked as expectation.
 
**To Reproduce**
```typescript
const rpcProvider = new RpcProvider({
    nodeUrl: `https://${
        StarknetNetwork.name.toLowerCase().includes("goerli")
            ? "starknet-goerli"
            : "starknet-mainnet"
    }.infura.io/v3/${process.env.INFURA_TOKEN}`,
})

const contractAddr = StarknetNetwork.address.TokenBridge.ETH
let nowNonce = await rpcProvider.getNonceForAddress(contractAddr)
let nowBlock = (await rpcProvider.getBlock()).block_number

console.log(contractAddr,"'s nonce in", nowBlock, "is", nowNonce.toString())
```

**Expected behavior**
Expected return is
```
0x073314940630fd6dcda0d772d4c972c4e0a9946bef9dabf4ef84eda8ef542b82 's nonce in 609106 is 490733
``` 
But the return is:
```
0x073314940630fd6dcda0d772d4c972c4e0a9946bef9dabf4ef84eda8ef542b82 's nonce in 609106 is 0
```

**Comment by ChiHaoLu** [comment]
I found the [statement](https://docs.starknet.io/documentation/getting_started/cli/index.html#get-nonce) in the StarkNet CLI Tool: 
> Note that the nonce returned by this command is advanced only once the transaction reaches the pending (or later) state.

Maybe it is the problem I met?

**Comment by tabaktoni** [comment]
After testing on devnet and gorily it seems that getNonceForAddress works correctly. Nonce is a critical component and none of the tests will pass if it doesn't work correctly.

The bridge is not an Account contract as so it will not give you a nonce increase.
