### ISSUE TITLE
`stark.compileCalldata` with Array of struct

### ISSUE THREAD

**Issue by Lerwox** [0xs34n/starknet.js#497]
In the documentation, we find the following behavior for compiling data of type Uint256
```js
const transferCallData = stark.compileCalldata({
  to: recipient,
  token_id: { type: 'struct', low: token.low, high: token.high },
});
```

I also read that you can directly pass an Array, and it automatically fills the `{}_len`.
```js
const arr = [1, 2 ,3];
const transferCallData = stark.compileCalldata({
  to: recipient,
  token_ids: arr,
});
```

So I naively thought that I could pass an Array of `{ type: 'struct' ...}`

```js
const arr = [
	{ type: 'struct', low: 1, high: 0 },
	{ type: 'struct', low: 2, high: 0 },
	{ type: 'struct', low: 3, high: 0 },
];
const transferCallData = stark.compileCalldata({
  to: recipient,
  token_ids: { type: 'struct', low: token.low, high: token.high },
});
```

But when I execute, I get an `Uncaught Error Error: Assertion failed` error.  
Am I doing it wrong? Maybe I should transform my list first, but `{}_len` must always be correct, So in the example : 
`{}_len` = 3 and not 6.
Imo, it would be cool to be able to pass directly the filled array 

EDIT : mb,  I misread [this part of the documentation](https://www.starknetjs.com/guides/define_call_message#object), it has all the info I need. But it would still be cool to pass an Array of struct.

**Comment by tabaktoni** [comment]
Please take a look at this PR description and give u feedback (it will resolve your issue, but it is highly probable it will be in v5 because of breaking changes)
https://github.com/0xs34n/starknet.js/pull/498

**Comment by tabaktoni** [comment]
Thank you for your feedback, I am closing now this issue as it is part of mentioned PR changes.
