### ISSUE TITLE
Create versions for API and Guides in the docs

### ISSUE THREAD

**Issue by ivpavici** [0xs34n/starknet.js#503]
For example - add a dropdown in the docs, so users can select v3, v4 or v5 for StarkNet JS API and guides

**Comment by PhilippeR26** [comment]
Will not be complicated to implement.

Level of granularity of versioning has to be defined for the starknet.js project . Several possibilities : 
- each major version
- each release
-  each minor version.
My feeling is that each release could be a good solution.

**Comment by ivpavici** [comment]
Currently, every release triggers a new doc build
