### ISSUE TITLE
(0.11.0) Expose Poseidon ZK-friendly hash function to users

### ISSUE THREAD

**Issue by ivpavici** [0xs34n/starknet.js#513]
**Is your feature request related to a problem? Please describe.**
Expose Poseidon, the ZK-friendly hashing function from https://github.com/paulmillr/noble-curves , to users
probably just: https://github.com/0xs34n/starknet.js/blob/develop/src/utils/ec.ts

**Comment by ivpavici** [comment]
blocked by https://github.com/0xs34n/starknet.js/issues/527

**Comment by ivpavici** [comment]
https://github.com/0xs34n/starknet.js/blob/develop/src/utils/ec.ts

**Comment by tabaktoni** [comment]
Exposed entire micro-starknet as starknetCurve in ec ``ec.starkCurve.utils.randomPrivateKey();``
Exposed poseidon from noble curves as poseidon in hash ``hash.poseidon``
```
export * as poseidon from '@noble/curves/abstract/poseidon';
export * as starkCurve from 'micro-starknet';
```
This should be all required exports from libs.
