### ISSUE TITLE
getStarkName() should return empty string when no starkname found

### ISSUE THREAD

**Issue by irisdv** [0xs34n/starknet.js#519]
**Describe the bug**

Currently `account.getStarkName()` returns "stark" when address has no stark name. 
This is due to `useDecoded` function in starknetId utils which concat "stark" at the end of the result from the call to the the starknet.id naming contract, even if it's empty.

https://github.com/0xs34n/starknet.js/blob/b0f4b7690b471b1c8edbbebaa4f9b64feb124d00/src/utils/starknetId.ts#L22

**To Reproduce**

```
const account = new Account(provider, address, ec.genKeyPair())
const result = await account.getStarkName()
```

**Expected behavior**
`account.getStarkName()` should return an empty string when address has no associated stark name. 

**Desktop (please complete the following information):**

- Node version `19.4.0`
- StarkNet.js version : `4.15.0`
- Network `devnet`

**Comment by fricoben** [comment]
Agree 🔥

**Comment by janek26** [comment]
empty string, or throw?

One thing that I would like to see is also to move the starkname methods from defaultAccount to the provider implementations.

I will take this one
