### ISSUE TITLE
'number' export conflicts with typescript default type 'number'

### ISSUE THREAD

**Issue by wraitii** [0xs34n/starknet.js#521]
**Describe the bug**
The 'number' export in starknet has the same name as the typescript built-in 'number' type, which is confusing both for me and my code editor.

**Expected behavior**
Starknet.js should probably not use such a common namespace for an export.

---

Version: Present in `develop` branch as of Feb 16 2023.

---

NB: the same applies to 'json', though that doesn't conflict the JS object which is capitalised, and probably some other ones.
NB2: I realise this is fairly debatable but I've had to alias the import or just use a top-level `starknet` import, and it seems slightly inconvenient.

**Comment by dhruvkelawala** [comment]
This has been the issue since the first day of starknet.js . I have pushed numerous times to go away from `numbers` namespace. It is surely to be fixed with v5. Do you have any suggestion as to what it can be called?

**Comment by ivpavici** [comment]
Rename to just `num` ?

**Comment by irisdv** [comment]
I can work on this
