### ISSUE TITLE
Improve user experience for migration to v5.0

### ISSUE THREAD

**Issue by PhilippeR26** [0xs34n/starknet.js#539]
**Is your feature request related to a problem? Please describe.**

When I try to migrate to V5.0 DAPP code made with V4, I have many compilation errors. Reasons are functions deprecated, renamed, relocated. Also end of BN format.  
When trying to correct the DAPP code, functions expected in `hash` are somewhere else.

**Describe the solution you'd like**

Ideally, a migration to V5 should be flawless, without any errors.  
For some subjects, I consider that it's impossible (BN replaced by bigint), but for many others, it can be easily corrected.

**Describe alternatives you've considered**
Not considered.

**Additional context**

Useful functions that have been identified as removed in V5.0 :
1. ec/hash/number :
``` 
hash.pedersen
ec.getKeyPair
ec.getStarkKey
keyPair.getPublic
keyPair.getPrivate
ec.getKeyPairFromPublicKey
ec.verify
ec.sign
number.toFelt
```
> Most of hash related functions are now in `ec`. They should be relocated in `hash`.

2. account/contract :
```
account.declareDeploy
```
3. provider
```
waitForTransaction, getTransactionStatus, addTransactionResponse, .chainId, 
"network:" when creating a new Provider.
```

We have also some errors when trying to pass/receive parameters to a smart-contract :
```
account.execute(multicall : Invocation[])  // invocation unknown
account.execute(addr,entry,calldata) // calldata unknown.
.call : result.balance // do not exist.
```

There are probably other cases, but the most common should be there.

**Comment by ivpavici** [comment]
@dhruvkelawala hey! can you maybe give your input re. hashes and `ec` ?

**Comment by PhilippeR26** [comment]
Sorry, I didn't understood your request.

**Comment by ivpavici** [comment]
cc: @penovicp

**Comment by ivpavici** [comment]
Agreed that a migration guide in docs would be very helpful!

**Comment by PhilippeR26** [comment]
OK. In progress.
