### ISSUE TITLE
migration 4.22 -> 5.1.0 - contract.call and provider.waitForTransaction

### ISSUE THREAD

**Issue by PhilippeR26** [0xs34n/starknet.js#547]
**Describe the bug**
- contract.call return type changed in V5. V4 code do not compile anymore.
- provider.waitForTransaction V4 code no more compile in V5.

**To Reproduce**
- contract.call
In V4, this code with contract.call and contract.meta-class is working : 
![image](https://user-images.githubusercontent.com/81040730/223152639-093f6ef5-b4b1-4e3f-9741-9ec79f9a8103.png)
bal1 type is `any`
bal1b type is `Result` : 
![image](https://user-images.githubusercontent.com/81040730/223152959-990b4079-5c98-4c78-adae-493de78ff17e.png)

In V5.1.0, I have these errors : 
![image](https://user-images.githubusercontent.com/81040730/223153482-3359ba25-e50a-44a5-9e70-00ceedae9f45.png)
`bal1` type is still `any`
`bal1b` type changed to `Object`  
`bal1.res` still operates.
`bal1b.res` no more compile (_'res' property do not exists in type 'Object'_)
- provider.waitForTransaction
compilation error in V5 : _2 args expected, but 1 received_. Seems to be an optional parameter that is not really optional.

**Expected behavior**
-  contract.meta-class has migrated flawlessly. Same thing is expected from contract.call.
-  provider.waitForTransaction flawless migration.

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker] N/A
- Node version [e.g. 16.0.1]ts-node v10.9.1
- Starknet.js version v4.22 & 5.1.0
- Network [devnet, testnet] devnet

**Comment by penovicp** [comment]
The `waitForTransaction` typing mismatch was resolved with #548.

It probably makes sense to swap the `CallData` and `Contract` usages of the `Object` type with something that allows for arbitrary keys.

**Comment by PhilippeR26** [comment]
In v4.22 it was : 
https://github.com/0xs34n/starknet.js/blob/b34c6e35728757c352d0ded7fa7cc89d4d79c7f0/src/types/contract.ts#L3-L5
