### ISSUE TITLE
How do we use starknet.js to check balance of particular address?

### ISSUE THREAD

**Issue by xcymo** [0xs34n/starknet.js#566]
I've checked Provider, there is no method like BalanceOf() in ethers.js, how can I query it? 
Thanks!

**Comment by ivpavici** [comment]
Hello! 
Please check these guides: https://www.starknetjs.com/docs/guides/interact
Regarding discord, we don't have for starknet.js specifically, but a channel in the official Starknet discord https://discord.gg/qypnmzkhbc

**Comment by xcymo** [comment]
Thanks!
