### ISSUE TITLE
Fix field "title" and related field in the RPC specs

### ISSUE THREAD

**Issue by ivpavici** [0xs34n/starknet.js#575]
Not in starknet.js code, but very related issue: https://github.com/starkware-libs/starknet-specs/issues/81#issuecomment-1490452130

Which fixing would help further development of future RPC versions, for example: https://github.com/0xs34n/starknet.js/issues/574

Estimated time to fix is couple of hours work

**Comment by ivpavici** [comment]
merged:
https://github.com/starkware-libs/starknet-specs/pull/84

**Comment by notV4l** [comment]
i can have a look at it

**Comment by notV4l** [comment]
autogeneration issues : 
https://github.com/starkware-libs/starknet-specs/issues/87

**Comment by ivpavici** [comment]
@tabaktoni  is the issue created by @notV4l relevant to us?

**Comment by tabaktoni** [comment]
From the issue, It look like rpc schema is not valid as so it is relevant to everyone

**Comment by notV4l** [comment]
attempt to fix some issues : https://github.com/starkware-libs/starknet-specs/pull/88
