### ISSUE TITLE
Cairo 1 Contract Interaction

### ISSUE THREAD

**Issue by tabaktoni** [0xs34n/starknet.js#579]
**Prerequisite**

Define the list of build-in types in Cairo 1
- [ ] felt -> felt252
- [ ] u8
- [ ] u16
- [ ] u32
- [ ] u64
- [ ] u128
- [ ] u256
- [ ] bool ?
- [ ] box ?
- [ ] nullable ?
- [ ] array (mix of types ?)
- [ ] ContractAddress
- [ ] Struct
- [ ] Tuple ??

Abi parsing 
- [ ] waiting for starknet update (abi methods missing types, no structures in abi ...)

**Implementation**

**Comment by PhilippeR26** [comment]
bool and usize.
Not sure for box and option.

**Comment by tabaktoni** [comment]
This look like to contain core types
https://github.com/starkware-libs/cairo/blob/3779d0db5968378061d40c30ab23932009e64b05/crates/cairo-lang-sierra/src/extensions/core.rs#L38
