### ISSUE TITLE
Support array-return values in contract

### ISSUE THREAD

**Issue by wraitii** [0xs34n/starknet.js#58]
[Contract::ParseResponse](https://github.com/seanjameshan/starknet.js/blob/develop/src/contract.ts#L105) does not support array-return types (X_len:felt, X: felt*). Instead the current method returns two variables with the length & the first value.

I am not clear whether Cairo intends to support struct return values, which also would entail changes to this function.

**Comment by seanjameshan** [comment]
Is this related to #105 or #106 ?

**Comment by dhruvkelawala** [comment]
Waiting on this to use with Multicall Contract Response. 
https://github.com/dhruvkelawala/argent-contracts-starknet/blob/main/contracts/Multicall.cairo

**Comment by MilGard91** [comment]
This is covered by the release v3.5.1 and is now part of the lib.

https://github.com/0xs34n/starknet.js/releases/tag/v3.5.1
