### ISSUE TITLE
Account @param cairoVersion

### ISSUE THREAD

**Issue by gaetbout** [0xs34n/starknet.js#591]
Now it is possible to declare a Contract. to be a Cairo1 contract using cairoVersion = '1': 
```js
constructor(abi: Abi, address: string, providerOrAccount?: ProviderInterface | AccountInterface, cairoVersion?: string);
```

But this is not possible for an Account:
```js
constructor(providerOrOptions: ProviderOptions | ProviderInterface, address: string, pkOrSigner: Uint8Array | string | SignerInterface);
```

It should be possible to specify it, so that the calldata are parsed using the new way of parsing data.

**Comment by tabaktoni** [comment]
cairoVersion was initali added to Contract class but will be removed as we don't use it.
In the Contract case we know from ABI that contract is Cairo1 or Cairo0

**Comment by gaetbout** [comment]
How'd you do in when the ABI is not loaded and directly using compileCalldata?

**Comment by tabaktoni** [comment]
At the moment we supported 
```ts
contratcX = new Contract(abi, address, account)
contractX.method(param1, param2, param3)
```
In this case ABI is not optional parameter.

Dev call on CallData.compile still need to be updated to support cairo 1 precompilation (bool uint252) and in this case probably CallData.compile will have cairoVersion flag.

**Comment by gaetbout** [comment]
Atm I'm using 
```
const { transaction_hash: transferTxHash } = await account.execute(
    {
      contractAddress: erc20Address,
      entrypoint: "transfer",
      calldata: CallData.compile([to.address, amountToTransfer, "0"]),
    },
    undefined,
    {  cairoVersion: "1" },
  );
  ```
  And it works as expected. 
  So I'm not sure to understand what you mean by:
  "Dev call on CallData.compile still need to be updated to support cairo 1 precompilation"

**Comment by tabaktoni** [comment]
Closing with remark:
uint26 fixed, bool fixed, CallData.compile will not recompile provided array []
