### ISSUE TITLE
Undefined block responses in goerli-alpha

### ISSUE THREAD

**Issue by aalimsahin** [0xs34n/starknet.js#593]
The response from the getBlock() function called with provider contains too many undefined for goerli-alpha. When the same query is made for mainnet-alpha, the expected response comes in full. But it doesn't work the same for goerli-alpha.

Below I am sharing the responses I have received so far.

The response for the GetBlock() function called for mainnet-alpha:
```
accepted_time: 1682178352
block_hash: "0x69e287bd14f3887736ec2ba7adffbc767a4a136bb215b837c14e7da59baa583"
block_number: 43276
gas_price: "0x899cdcab0"
new_root: "04bd91d08eee8e2bc6df5d56e81860c6b6e56b0a81de67d4e00ac76fe1135a83"
old_root: undefined
parent_hash: "0xfdfde00d49a446ec2bb85fcab6bc9f22f816b5045d039ccc3d54460102d788"
sequencer: "0x1176a1bd84444c89232ec27754698e5d2e7e1a7f1539f12027f28b23ec9f3d8"
status: "ACCEPTED_ON_L2"
transactions: string[]
```

The response for the GetBlock() function called for goerli-alpha:
```
accepted_time: 1682178740
block_hash: undefined
block_number: undefined
gas_price: "0x6dc"
new_root: undefined
old_root: undefined
parent_hash: "0x294127e23e2abd883e3215e6af9ca67fa05250ee225a35b4dca1bc8b1f3a816"
sequencer: "0x1176a1bd84444c89232ec27754698e5d2e7e1a7f1539f12027f28b23ec9f3d8"
status: "PENDING"
transactions: string[]
```

**Comment by ivpavici** [comment]
Hello! these are different blocks, if you check the statuses, one is ACCEPTED_ON_L2 and the other is PENDING, so it makes sense that you observe undefined properties... also, starknet.js should not experience any difference between mainnet and testnet, we don't differentiate between the two...
