### ISSUE TITLE
Deploy account using Cairo1 structure

### ISSUE THREAD

**Issue by gaetbout** [0xs34n/starknet.js#594]
At the moment it isn't possible to deploy or declare an Account using `cairoVersion = '1'.`

It should be possible to specify which cairoVersion the account is and relevant deploy and declare fn should take it into consideration. 
This cairoVersion is already carried at several places, but it isn't taken into consideration.

**Comment by tabaktoni** [comment]
deploy contract is generic and should work, can you specify an example of an issue ?
deployAccount is not adapted to Cairo 1 yet because we just recently got the first Account rewritten in Cairo 1 to test width.

**Comment by gaetbout** [comment]
Would you have any ETA regarding cairo1 account support? 😄

**Comment by tabaktoni** [comment]
I'm working on it at the moment, so I hope this week

**Comment by tabaktoni** [comment]
To clarify:
- All operations from Cairo0 Account should work from before
- Deploy Cairo1 account from Caito0 account should also work (deployAccount) from before

What I need to test is:
- Deploy Cario 1 account from Cairo 1 account
- All operations from Cairo 1 account

**Comment by gaetbout** [comment]
When I try to deploy a Cairo1 account I'm running into 'Input too long for arguments', is it normal?
Doing it from a Cairo0 account as follow:
```rust
  const { transaction_hash } = await accountToDeploy.deployAccount(
    {
      classHash: accountClassHash,
      constructorCalldata,
      contractAddress,
      addressSalt: publicKey,
    },
    {
      cairoVersion: "1",
    },
```

**Comment by gaetbout** [comment]
Not doing it from a cairo0 account but funding it then executing deployAccount (it should be able to pay for its own deployment), made a mall mistake.

**Comment by tabaktoni** [comment]
Here i added test for it in this open PR so you can take a look into it:
https://github.com/0xs34n/starknet.js/blob/0ef1ec8624e294a526f8e97d856e70b6426a9ae3/__tests__/account.test.ts#L107
cairoVersion flag should only be used when you use cario 1 Account, even thoe i am still working on that as flag were intermidiate fix. So if you do stuff from Cartio 0 Account you don't use any flags.

```ts
const { transaction_hash } = await accountToDeploy.deployAccount(
    {
      classHash: accountClassHash,
      constructorCalldata,
      addressSalt: publicKey,
    })
```

**Comment by tabaktoni** [comment]
Resolved
