### ISSUE TITLE
deploy account error

### ISSUE THREAD

**Issue by GuoyiZhang** [0xs34n/starknet.js#623]
**Describe the bug**
GatewayError: Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:163)
Unknown location (pc=0:139)

**Screenshots**
<img width="1594" alt="image" src="https://github.com/0xs34n/starknet.js/assets/17961901/1df8f0ee-157c-4646-970c-2a895557f12a">

- Browser & version [e.g. chrome, safari, webworker]
- Node version [e.g. 16.0.1]
- Starknet.js version      "starknet": "^4.13.0",
- Network [devnet, testnet].  mainnet

**Additional context**

**Comment by GuoyiZhang** [comment]
const account = new Account(provider_starkNet, accountAddress, starkKeyPair);
    const ClassHash = '0x03131fa018d520a037686ce3efddeab8f28895662f019ca3ca18a626650f7d1e';
    let implementation = "0x5aa23d5bb71ddaa783da7ea79d405315bafa7cf0387a74f4593578c3e9e6570";
    const constructorCallData = stark.compileCalldata({
        implementation: implementation,
        selector: "0x2dd76e7ad84dbed81c314ffe5e7a7cacfb8f4836f01af4e913f275f89a3de1a",
        calldata: stark.compileCalldata([starkKeyPub]),
    });

    console.log(constructorCallData);
    const deployAccountPayload = {
        classHash: ClassHash,
        constructorCalldata: constructorCallData,
        contractAddress: accountAddress,
        addressSalt: starkKeyPub,
    };
    console.log(deployAccountPayload);

    const {transaction_hash, contract_address} = await account.deployAccount(
        deployAccountPayload
    );

**Comment by GuoyiZhang** [comment]
learn demo https://github.com/0xs34n/starknet.js-account/blob/main/index.js


const account = new Account(testnetOneProvider, contractAddress, starkKeyPair);

const deployAccountPayload = {
  classHash: argentProxyClassHash,
  constructorCalldata: constructorCallData,
  contractAddress: contractAddress,
  addressSalt: starkKeyPublic,
};

const { transaction_hash, contract_address } = await account.deployAccount(
  deployAccountPayload
);

console.log(`\nAccount contract deployment in progress...\n`);
console.log(
  `Check deployment transaction status at \n\nhttps://testnet.starkscan.co/tx/${transaction_hash}\n`
);
console.log(
  `Once the transaction is confirmed. The account is deployed at \n\nhttps://testnet.starkscan.co/tx/${contract_address}\n`
);

**Comment by GuoyiZhang** [comment]
<img width="203" alt="image" src="https://github.com/0xs34n/starknet.js/assets/17961901/77fa498a-ca04-4c0a-88c4-f09c3af1bc07">

**Comment by GuoyiZhang** [comment]
Error in the called contract (0x348fe899270bd091015bf0b5f2313b3f88707c7300e48d051c1fa720b02c8d6):
Error message: Account: missing parameters in initializer signature
Error at pc=0:114:
An ASSERT_EQ instruction failed: 2 != 10.
Cairo traceback (most recent call last):
Unknown location (pc=0:163)
Unknown location (pc=0:130)

**Comment by ivpavici** [comment]
Hello! I think you are using a very outdated tutorial!
I suggest playing with this one: https://github.com/PhilippeR26/starknet.js-workshop-typescript 
You can ask Phil any questions on his repo!
