### ISSUE TITLE
DRAFT: Intorduce v0 transactions in v5

### ISSUE THREAD

**Issue by tabaktoni** [0xs34n/starknet.js#631]
Enable composing v0 and v1 and v2 transactions.
Explain what exact transactions are required by wallets?

- Provide 'simple flow' invoke v0 transaction (no need for bulk's impl.)

**Comment by yoga-braavos** [comment]
@tabaktoni , in general we would like users to be able to call the `upgrade` entrypoint with v0 transaction so that they can upgrade to v1 compatible account contract.

**Comment by ivpavici** [comment]
related: https://github.com/0xs34n/starknet.js/issues/465

**Comment by dhruvkelawala** [comment]
My opinion is not doing this. For tx v0, starknet.js v4 should be used. In this case, it would just be for "upgrade" txns. Wallets will know if it's an old account or new and can use starknet.js versions accordingly.
