### ISSUE TITLE
Correclty define ContractClasses types, fix provider common type

### ISSUE THREAD

**Issue by tabaktoni** [0xs34n/starknet.js#634]
**Describe the bug**
Sequencer and RPC requests and responses are different in the case of the ContractClass format.
ContractClass, CompiledContract, CairoContract

- [] evaluate all ednpoint's responses format (rpc and Sequencer)
- [] evaluate all declare format (rpc and Sequencer)
- [] define an internal type that will serve as a common type for both pre-requests without breaking changes

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- Node version [e.g. 16.0.1]
- Starknet.js version
- Network [devnet, testnet]

**Additional context**

**Comment by tabaktoni** [comment]
@PhilippeR26 Can you please add your examples, test, and evaluation mentioned on discord?

**Comment by PhilippeR26** [comment]
Example of problem in mainnet, with a Cairo 1 problem : 
```typescript
const addrErc20 = "0x060cf64cf9edfc1b16ec903cee31a2c21680ee02fc778225dacee578c303806a";
const testContract = await provider.getClassAt(addrErc20);
const testAbi2 = testContract.abi ;
console.log("typeof =",typeof testAbi2,", is array =",Array.isArray(testAbi2));
```
The compiler indicates that 
- testContract is : `ContractClass | CONTRACT_CLASS`
- testAbi2 is `Abi` type : `Abi | CONTRACT_ABI | undefined`
If the provider is using the sequencer, it works fine : I can create an Account object using this abi ; the result in the console is : 
```
typeof = object , is array = true
```
If the provider is using rpc (local pathfinder or alchemy), the result is :
```
typeof = string , is array = false
```
This false `Abi` object is crashing Starknet.js  at account object creation.

1. provider.getClassAt() and provider.getClassByHash() should have from an user point of view only one type, whatever how the provider is connected.
2. .abi should have from an user point of view only one type, whatever provider connection and Cairo 0/1. this object has to be really of` Abi` type in all cases.

**Comment by notV4l** [comment]
on it
