### ISSUE TITLE
pedersen hash performances

### ISSUE THREAD

**Issue by notV4l** [0xs34n/starknet.js#638]
**Is your feature request related to a problem? Please describe.**
`computeLegacyContractClassHash` can take up to 8/10s (on my poor computer)
there is a lot of pedersen hash calls

**Describe the solution you'd like**
use a wasm version of pedersen hash
i tried to use https://github.com/l2beat/pedersen-fast which is 100x faster
it uses rust/wasm and its built for node.js (i tested and it help a lot to speed up tests too)
it should be possible to build it for browser too ?

**Additional context**
i guess cairo0 will soon be deprecated, so maybe not worth XD

**Comment by tabaktoni** [comment]
@notV4l Can we close this issue, as we do not have a universal solution:

- Wasm drawbacks are code transparency, and this is critical peace where we want to reduce dependency.
- No browser support
- Cairo 0 deprecation
- providing classHash and compiledClassHash will would have even better performance gains.
