### ISSUE TITLE
Support Cairo 1 Compiler 2.0

### ISSUE THREAD

**Issue by tabaktoni** [0xs34n/starknet.js#651]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by janek26** [comment]
Would be nice if this can be done rather sooner than later 🙏 In that case many Dapps and wallets could skip cairo1 with compiler v1 entirely, and integrate with cairo1 with compiler v2 directly

**Comment by PhilippeR26** [comment]
I found an example in the Cairo 1 repo, version 2.0.0-rc5.
You have the .cairo, .sierra.json and the .casm.json here :
https://github.com/starkware-libs/cairo/blob/v2.0.0-rc5/crates/cairo-lang-starknet/test_data/new_syntax_test_contract.cairo

**Comment by PhilippeR26** [comment]
So, we have now :
- abi from a cairo 0 contract
- abi from a cairo 1 v0.6.0 or v1.1.0 contract
- abi from a cairo 1 v2.0.0
And there is no field to indicate the version of the abi format...
The situation become rather complicated!

**Comment by tabaktoni** [comment]
Outdated, Resolved
