### ISSUE TITLE
LibraryError: -32603: Sending V1 invoke transaction to gateway

### ISSUE THREAD

**Issue by bright1989** [0xs34n/starknet.js#652]
When I use Rpc Provider to call the contract, it will report an error: Sending V1 invoke transaction to gateway
But when using the Sequencer Provider, it can execute correctly

**Comment by ivpavici** [comment]
Hello!
Can you please provide some code?

**Comment by Lyagushe4ka** [comment]
Have the same issue, just using `RpcProvider` class and infura rpc instead of `Provider` class and default 'mainnet-alpha' and trying to send a mullticall (approve + bridge router function) and keep getting:

LibraryError: -32603: Sending V1 invoke transaction to gateway
    at RpcProvider.errorHandler (/Users/Projects/node_modules/starknet/src/provider/rpc.ts:88:13)
    at RpcProvider.fetchEndpoint (/Users/Projects/node_modules/starknet/src/provider/rpc.ts:99:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Lyagushe4ka** [comment]
i got something like this

```
const provider = new RpcProvider({ nodeUrl: "https://starknet-mainnet.infura.io/v3/YOUR_KEY" });
const account = new Account(provider, starkAddress, starkPrivateKey);
const tokenIsntance = new Contract(starkErc20Abi, tokenAddress, provider); // ETHER
const routerInstance = new Contract(starknetOributerRouterAbi, orbiterRouters.Starknet.orbiterContract, provider); // orbiter router

const value = ethers.utils.parseEther(amount.toFixed(6)).add(BigNumber.from(9002)); // 9002 -  Arbitrum chainId 
const valueUint256 = uint256.bnToUint256(value.toString());
const maxUint = uint256.bnToUint256(uint256.UINT_256_MAX);

const value = ethers.utils.parseEther('0.006').add(BigNumber.from(9002)); // 0.006 ether + 9002 - Arbitrum chain id
const valueUint256 = uint256.bnToUint256(value.toString());

// im sure that i have enough balance

let tx: any;
try {
  tx = await account.execute(
    [
      {
        contractAddress: '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7', // ETH
        entrypoint: "approve",
        calldata: stark.compileCalldata({
          spender: '0x0173f81c529191726c6e7287e24626fe24760ac44dae2a1f7e02080230f8458b', // orbiter router
          amount: {type: 'struct', low: maxUint.low, high: maxUint.high},
        })
      },
      {
        contractAddress: routerInstance.address,
        entrypoint: "transferERC20",
        calldata: stark.compileCalldata({
          _token: '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7', // ETH
          _to: '0x07b393627bd514d2aa4c83e9f0c468939df15ea3c29980cd8e7be3ec847795f0', // orbiter wallet
          _amount: {type: 'struct', low: valueUint256.low, high: valueUint256.high},
          _ext: EVM_ADDRESS, // your evm address to bridge funds
        })
      }
    ]
  );
} catch (e: any) {
  console.log('error sending tx', e);
}
    
const receipt = await provider.waitForTransaction(tx.transaction_hash)
```
    
    lib version: "starknet": "^4.22.0"
    
    and i keep getting an error that i sent earlier

**Comment by ivpavici** [comment]
This is most probably the issue:
lib version: "starknet": "^4.22.0" 

Can you try with the latest pre-release version (develop branch, v5.13.2):
$ npm install starknet@next

**Comment by Lyagushe4ka** [comment]
got it, will try, thanks!

**Comment by Lyagushe4ka** [comment]
a bit different issue apart the name but i faced it just at the very beginning of my migration from v4

as long as `ec.getKeyPair()` got depricated and `ec.getStarkKey(keyPair)` changed to `ec.starkCurve.getStarkKey(privateKey)`

I no longer can get the public key from the basic 64 symbols long (32 bytes) evm private key?
because i get ```if (!isWithinCurveOrder(num)) throw new Error('Expected valid bigint: 0 < bigint < curve.n');```

only ones generated by `stark.RandomAddress()` are valid which are 63 symbols long (with leading zero i guess) and aren't out of the EC?

**Comment by PhilippeR26** [comment]
Not sure to understand your question.
But probably answers here : https://starknetjs.com/docs/next/guides/signature

**Comment by tabaktoni** [comment]
Original issue is resolved i guess @bright1989 ?
Second issue is resolved @Lyagushe4ka ?

**Comment by tabaktoni** [comment]
Close due inactivity, if you encounter this problem please open a new Issue.
