### ISSUE TITLE
Make `estimateFee` comply with specs

### ISSUE THREAD

**Issue by exp-table** [0xs34n/starknet.js#666]
**Describe the issue**
`estimateFee` doesn't comply with the latest RPC [specs](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L488).

**Expected behavior**
According to latest specs, only an array of transactions can be passed.

**Comment by penovicp** [comment]
The `ProviderInterface` that `SequencerProvider` and `RpcProvider` implement is based on both the `JSON RPC` and `Gateway/FeederGateway API` specifications which don't always fully align. 

For the fee estimation functionality the `Gateway API` has two endpoints, one for individual estimates and one for bulk estimates, for which corresponding methods were added to the `ProviderInterface`. When at a later time the bulk estimate functionality was added to RPC nodes it was chosen that it would be made available in `starknet.js` through the existing `getEstimateFeeBulk` method ([link](https://github.com/0xs34n/starknet.js/blob/v5.15.1/src/provider/rpc.ts#L320)).
 
 This will probably not change at least until the `SequencerProvider` is deprecated.
