### ISSUE TITLE
Add 'Calldata' type as input of contract meta-classes

### ISSUE THREAD

**Issue by PhilippeR26** [0xs34n/starknet.js#684]
**Is your feature request related to a problem? Please describe.**
Contract meta-class do not accept as input the result of the following functions : 
- myContract.populate().calldata
- myCallData.compile()
- Calldata.compile()

The results are of type `Calldata`

**Describe the solution you'd like**
This code should work :
```typescript
const functionParameters: RawArgsObject = {
        val1: 1,
        amount: cairo.uint256(15),
    }
    const myCall0: Call = myTestContract.populate("test9", functionParameters);
    const res17 = await myTestContract.test9(myCall0.calldata);

    const contractCallData: CallData = new CallData(compiledTest.abi);
    const myCalldata: Calldata = contractCallData.compile("test9", functionParameters);
    const res19 = await myTestContract.test9(myCalldata);

    const contractCallData2: Calldata = CallData.compile(functionParameters);
    const res20 = await myTestContract.test9(contractCallData2);
   ```

**Describe alternatives you've considered**
Use of `...myCall0.calldata` works only if the number of parameters is not increased by populate/compile (u256 is adding one parameter) :
```typescript
const res17 = await myTestContract.test9(...myCall0.calldata);
```
This code do not work with u256 as input.

**Additional context**
I will propose a PR for this subject.

**Comment by tabaktoni** [comment]
Resolved in [v5.17.0](https://github.com/0xs34n/starknet.js/releases/tag/v5.17.0)
