### ISSUE TITLE
Update Guide highlight IMPORTANT! cairoVersion in Accont Class or make it mandatory

### ISSUE THREAD

**Issue by tabaktoni** [0xs34n/starknet.js#686]
**Is your feature request related to a problem? Please describe.**
At the moment all wallets operate with Cairo0 Account contracts. We have the optional flag `cairoVersion` in Account Class that indicates the version of Account in use. By default `cairoVersion` is set to 0, and is not a required parameter.
As @LucasLvy indicated this can be confusing, and the proposed solution is to set it to be the mandatory parameter.
It will produce interface change and a chain reaction of required updates -> wallets -> daps -> get-starknet -> stargate ...

**Describe the solution you'd like**
To resolve the transition period I propose that:
1. until all wallets switch to the default Cairo 1 Account's implementation, leave cairoVersion 0 as is.
2. when all wallets update to default Cairo 1 Account implementation, switch to default 1.
3. Highlight this parameter in the documentation as IMPORTANT! now, and explain its behavior and expected default change.
4. After regenesis and removal of Cairo0 support this parameter will be removed

This way we will not break the interface and eventually switch to the new Cairo1 standard.

**Describe alternatives you've considered**
Set the `cairoVersion` flag as mandatory

@LucasLvy @janek26 @dhruvkelawala @yoga-braavos @penovicp @ivpavici @PhilippeR26

**Comment by ivpavici** [comment]
@PhilippeR26 let's do this in docs?
