### ISSUE TITLE
The calldata of the transaction that is not parsed through abi is an object

### ISSUE THREAD

**Issue by liuhuanhui** [0xs34n/starknet.js#687]
Try to use the Calldata in the starknetjs 5.14.1 version package to parse and format, but the desired data is not parsed. The data returned by parse and format are both success: 1n }. Can't the calldata be restored to the object through abi?

**Comment by tabaktoni** [comment]
Please do not delete bug template when posting issue else we need to go back and forward with questions.

Could you give us more context to debug your issue (what type of data Structs, tuples, tuples in tuples in struct...)?
Can you provide a minimal example to reproduce your issue?

**Comment by tabaktoni** [comment]
Close due to inactivity
