### ISSUE TITLE
waitForTransaction is waiting too much time

### ISSUE THREAD

**Issue by PhilippeR26** [0xs34n/starknet.js#688]
**Is your feature request related to a problem? Please describe.**
Until now, Starknet was a little ... slow, the `provider.waitForTransaction ()` is first waiting 8 seconds before testing the transaction status. If necessary, it's retested each 8s.

https://github.com/0xs34n/starknet.js/blob/7bc96fae09c4cfb0427b622794be884d3dc4e554/src/provider/sequencer.ts#L495

https://github.com/0xs34n/starknet.js/blob/7bc96fae09c4cfb0427b622794be884d3dc4e554/src/provider/rpc.ts#L442

But now, Cairo_lang 0.12.0 is installed in all Starknet networks, and all is much much faster.
These 8s of wait seems to be no more adapted to the "new" Starknet, and should be reduced

**Describe the solution you'd like**
I propose to reduce this value to something between 4 and 5s.

**Describe alternatives you've considered**
Be patient... even when Starknet has already ended the job...

**Additional context**

**Comment by PhilippeR26** [comment]
https://twitter.com/Starknet/status/1679762624756715520?t=ww4tn0u59aAXb_E8RZLICg&s=19

**Comment by tabaktoni** [comment]
For now i will leave it as is.
Check mainet transaction time https://voyager.online/analytics?page=network
it is between 30-50 sec

**Comment by PhilippeR26** [comment]
Shall we consider time for block approval, or time to transaction Approved in L1?

**Comment by tabaktoni** [comment]
Reducer to 5sec in 0.12.1 RP
