### ISSUE TITLE
EventFilter : all parameters are now mandatory

### ISSUE THREAD

**Issue by PhilippeR26** [0xs34n/starknet.js#692]
**Describe the bug**
3 months ago, the PR #603 has modified the type EVENT_FILTER
![image](https://github.com/0xs34n/starknet.js/assets/81040730/6a6e265c-b627-451d-b870-4766a49f1ce1)
Previous code that do not filter `address` or `keys`, are no more working.

**To Reproduce**
This code was working fine  before this PR, and is no more working :
https://github.com/PhilippeR26/starknet.js-workshop-typescript/blob/main/src/scripts/mainnet/4.getEvents.ts

**Expected behavior**
`address` or `keys` are not mandatory on the node side : PathFinder and rpcDevnet accepts these parameters as optional.
So these 2 keys should be optional in EVENT_FILTER.
**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- Node version [e.g. 16.0.1]
- Starknet.js version : 5.16.0
- Network [devnet, testnet] : mainnet

**Additional context**

**Comment by tabaktoni** [comment]
Resolved in RPC 0.4.0-rc3 PR
