### ISSUE TITLE
Parsing of events

### ISSUE THREAD

**Issue by edisontim** [0xs34n/starknet.js#697]
**Is your feature request related to a problem? Please describe.**
Not related to a problem per se but it would facilitate the usage of events in Starknet js

**Describe the solution you'd like**
It's a hassle to read events coming from a contract for which we have the ABI available. I think it would be very nice to have a ParseEvent function available in the Contract class

For now I believe the only way of reading events is by parsing it manually: https://www.starknetjs.com/docs/guides/events

**Comment by edisontim** [comment]
I'm willing to implement this btw

**Comment by ivpavici** [comment]
Hello!
We already have an (old) issue open for this:
https://github.com/0xs34n/starknet.js/issues/112 

The issue was that nodes didn't have web sockets implemented... But there are developments in this area being done as we speak...

Does this "help" or you have a different use case in mind?

**Comment by edisontim** [comment]
I meant something different, after using ```provider.waitForTransaction(tx_hash)``` there can be a bunch of events emitted during that transaction, what I want to do is being able to call a ```parseEvent``` function of the ```contract``` object to parse the event's data into a useful format. Contract which I created with the ABI that has the definition of the event,

**Comment by tabaktoni** [comment]
Usage would be like?

```
const tx = myContract.increase_balance(1000);
waitForTransaction(tx.tx_hash)
const events = myContract.getEvents(tx.tx_hash);
```

where events would be nicely formatted and parsed events data based on ABI.
This is a good idea.
Before you start, if you have some additional solutions and use cases it will be good to describe them so we can discuss the final interface before implementation.

**Comment by edisontim** [comment]
I was thinking more of this: 
```
const tx = myContract.increase_balance(1000);
const transactionResult = await provider.waitForTransaction(tx.transaction_hash);
const events = myContract.getEvents(transactionResult);
```
Then you don't need to query the blockchain again as every event is already stored in ```transactionResult```, it would just find the events in ```transactionResult``` that match ```myContract.address```. Only thing I'm not sure of is how you would get from the event's name in the ABI formatted as such: 
```
{
	"kind": "struct",
	"name": "game::Game::StartGame",
	"type": "event",
	"members": [
	{
		"kind": "data",
		"name": "adventurer_state",
		"type": "game::Game::AdventurerState"
	},
	{
		"kind": "data",
		"name": "adventurer_meta",
		"type": "survivor::adventurer_meta::AdventurerMetadata"
	}
	]
},
```
to the ```event.key``` hash. Not sure how it's hashed

**Comment by PhilippeR26** [comment]
The hash of an event is :
```typescript
starkCurve.keccak(eventName)
```
It will be necessary to take care that the event can write in both keys and data array :
``` json
{
      "type": "event",
      "name": "PhilTest2::PhilTest2::MyTestContract::CounterIncreased",
      "kind": "struct",
      "members": [
        {
          "name": "from",
          "type": "core::starknet::contract_address::ContractAddress",
          "kind": "key"
        },
        {
          "name": "amount",
          "type": "core::integer::u128",
          "kind": "data"
        }
      ]
    },
```

**Comment by edisontim** [comment]
Yep, exactly what I had in mind, thank you for the input and the illustration!

**Comment by tabaktoni** [comment]
Ok, so implementation can be made in utils/events/responseParser.ts ?
Wrapper function in Contract Class that uses implementation
```ts
public parseEvents(receipt: GetTransactionReceiptResponse)
```

**Comment by tabaktoni** [comment]
@edisontim You can start working on this task

**Comment by tabaktoni** [comment]
> ```json
> {
>       "type": "event",
>       "name": "PhilTest2::PhilTest2::MyTestContract::CounterIncreased",
>       "kind": "struct",
>       "members": [
>         {
>           "name": "from",
>           "type": "core::starknet::contract_address::ContractAddress",
>           "kind": "key"
>         },
>         {
>           "name": "amount",
>           "type": "core::integer::u128",
>           "kind": "data"
>         }
>       ]
>     },
> ```
> 
> 
> The result could be (type ParsedEvent) :
> 
> ```ts
> {
> eventName : "CounterIncreased",
> keys: {from: "0x6c8fe36d7454901424063b5c1b949d7e347ce3872d2487b30b76f3a4fd7c219"},
> data: {amount: "0xa"}
> }
> ```

On this point final result should be js representation of data so for Struct of this types:
```ts
{
  CounterIncreased: {
    from: BigInt,
    amount: BigInt,
  }
}
```

**Comment by edisontim** [comment]
Implemented in https://github.com/0xs34n/starknet.js/pull/704

**Comment by edisontim** [comment]
Could someone have a look at the PR? The CI doesn't pass but I've tried to reproduce the failure locally and can't manage to @ivpavici ?

**Comment by edisontim** [comment]
> On this point final result should be js representation of data so for Struct of this types:

Had to slightly change the final representation as multiple events of the same type can be in the same receipt: 
```
{
  CounterIncreased: [
    {
      from: BigInt,
      amount: BigInt,
    },
    ...
  ]
}
```

**Comment by tabaktoni** [comment]
I agree this format is inconvenient. It can be flattened before return if the refractor is complicated easily by:
It can be flatter by:
```ts
Object.entries(d).map(i=>i[1].flatMap(t=>({[i[0]]:t}))).flat()
```
Even doe this can be used to flatter results now it is not trivial.

**Comment by edisontim** [comment]
Ok, I thought the format was easier but the change is done :)

**Comment by tabaktoni** [comment]
Resolved in https://github.com/0xs34n/starknet.js/pull/712
v5.19.0
