### ISSUE TITLE
Handling of new Cairo v2.0.0 types

### ISSUE THREAD

**Issue by PhilippeR26** [0xs34n/starknet.js#707]
**Describe the bug**
Starknet.js  is not handling properly some new Cairo types :
`ContractAddress, EthAddress, ClassHash, and Span`

**To Reproduce**
If you try to interact with such Cairo v2.0.0 functions, it will fail :
```rust
fn array_new_types(
            self: @ContractState,
            tup: (ContractAddress, EthAddress, ClassHash),
            tupa: (Array<ContractAddress>, Array<EthAddress>, Array<ClassHash>)
        ) -> (Array<ContractAddress>, Array<EthAddress>, Array<ClassHash>)
        
fn new_span(self: @ContractState, my_span: Span<u16>) -> Span<u16> 
```

**Expected behavior**
***1. ContractAddress & ClassHash :***
In Cairo code, they are considered as felt.
In ABI, they are considered as core litterals :
```json
{
  "name": "creator",
  "type": "core::starknet::contract_address::ContractAddress"
},
{
  "name": "ch",
  "type": "core::starknet::class_hash::ClassHash"
},
```
So, in DAPP code, they have to be considered as BigNumberish limited to 252 bits. 

***2. EthAddress :***
In Cairo code, it's considered as felt.
In ABI, it's considered as struct (!!!) :
```json
{
  "type": "struct",
  "name": "core::starknet::eth_address::EthAddress",
  "members": [
    {
      "name": "address",
      "type": "core::felt252"
    }
  ]
},
```
So, in DAPP code, they have to be considered with same type as in Cairo code :  BigNumberish limited to 160 bits. 

***3. Span :***
In Cairo code, it's considered as very close to Array (just immutable).
In ABI, it's considered as struct (!!!):
```json
{
  "type": "struct",
  "name": "core::array::Span::<core::integer::u16>",
  "members": [
    {
      "name": "snapshot",
      "type": "@core::array::Array::<core::integer::u16>"
    }
  ]
}
```
So, in DAPP code, they have to be considered with same type as in Cairo code :  Array. 

**Screenshots**
N/A

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- Node version [e.g. 16.0.1]
- Starknet.js version 5.17.0
- Network [devnet, testnet]

**Additional context**
N/A

**Comment by tabaktoni** [comment]
Resolved in https://github.com/0xs34n/starknet.js/pull/712
v5.19.0
