### ISSUE TITLE
Account constructor should accept numeric 1 for cairo version

### ISSUE THREAD

**Issue by ittayd** [0xs34n/starknet.js#724]
getExecuteCalldata is called from execute and has a cairoVersion argument that is passed as this.cairoVersion. It expects it to be a string, but it is intuitive to think of it as a number. If the Account is created with a number 1, it is silently treated as version 0 because 1 !== "1".

Also, seems to me that the account relies on the sierra version. It can be undefined to mean "pre sierra", or a version, to mean the compatible (that is, minimal) sierra version for this account's interface.

**Comment by PhilippeR26** [comment]
I think it's full of common sense.
Implemented in PR #571 by @dhruvkelawala .
I don't know if there is a spec requesting a string...
If we change, it will impact existing DAPPs using Cairo 1 accounts...

**Comment by tabaktoni** [comment]
It does not depend on the sierra version, as the Contract Interaction part is handled by ABI.
The only reason why this flag exists is __execute__ that changed interface in Cario1 described in #571.
We could update typing and docs with cleaner ways to represent this flag to avoid misuse as a number.
 In the future, this flag will be removed as wallets switch to Cairo1 Accounts and Cairo0 Accounts get deprecated.
