### ISSUE TITLE
provider.waitForTransaction options can't work

### ISSUE THREAD

**Issue by adolyb** [0xs34n/starknet.js#730]
Hello. I tried to wait the transcation util ACCEPTED_ON_L2. 

`await provider.waitForTransaction(multiCall.transaction_hash,{successStates:["ACCEPTED_ON_L2"]});`

But it still wait until ACCEPTED_ON_L1.

It takes long time

**Comment by PhilippeR26** [comment]
Hello,
Your transaction could also be rejected or reverted (with a node).
Are you connected with a rpc node, or with a sequencer?
Do you have a transaction hash with this behavior?

**Comment by lewisYe** [comment]
> 您好， 您的交易也可能被拒绝或恢复（通过节点）。 您连接的是 rpc 节点还是定序器？ 您能提供具有这种行为的交易哈希吗？



> Hello, Your transaction could also be rejected or reverted (with a node). Are you connected with a rpc node, or with a sequencer? Could you provide a transaction hash with this behavior?

I encountered the same situation , I used a rpc node , transaction is success. But it still wait

**Comment by lewisYe** [comment]
> Hello, Your transaction could also be rejected or reverted (with a node). Are you connected with a rpc node, or with a sequencer? Could you provide a transaction hash with this behavior?

I encountered the same situation , I used a rpc node , transaction is success. But it still wait

**Comment by PhilippeR26** [comment]
> I encountered the same situation , I used a rpc node , transaction is success. But it still wait
Which node provider are you using?
For which network?
What's your Starknet.js version?
Problems have been reported yesterday with Alchemy.

**Comment by lewisYe** [comment]
> 
Starknet.js version  5.19.3  , i use infura and blast node provider also have the problem。network is  starknet  mainnet. 
 use `const provider = new Provider({ rpc: { nodeUrl: 'xxx' } })`  to get provider

**Comment by PhilippeR26** [comment]
Thanks, 
Could you try with Starknet.js v5.19.5?

**Comment by tabaktoni** [comment]
Fixed by https://github.com/0xs34n/starknet.js/releases/tag/v5.19.5
