### ISSUE TITLE
cannot create the naming contract object of starknetid

### ISSUE THREAD

**Issue by YuPuiTsuens** [0xs34n/starknet.js#734]
I returned an error when using starknet.js to initialize the starknetid naming contract

LibraryError: -32603: Internal error: StarknetErrorCode.UNDECLARED_CLASS: Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:228)
Unknown location (pc=0:214)

Error in the called contract (0x6c84de1e7394c700d0d4a382db05b3186fee012e51daecc1c1e2caf1d5ecd94):
Error at pc=0:219:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:8090)
Unknown location (pc=0:8038)
Unknown location (pc=0:5734)
Unknown location (pc=0:5755)

Error in the called contract (0x6ac597f8116f886fa1c97a23fa4e08299975ecaf6b598873ca6792b9bbfb678):
Error at pc=0:15:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:214)
Unknown location (pc=0:200)

Error in the called contract (0x6ac597f8116f886fa1c97a23fa4e08299975ecaf6b598873ca6792b9bbfb678):
Class with hash 0x777ba3d99380d889d4cee7148a35c608c18bb4c993643cdfa013143346d9753 is not declared.

Or when I use getClassAt to get abi, return

LibraryError: 20: Contract not found

As a result, I cannot create the naming contract object of starknetid,
What should I do?

**Comment by penovicp** [comment]
It's best to reach out to Starknet.id on their Discord: [https://discord.gg/8uS2Mgcsza](https://discord.gg/8uS2Mgcsza).
